// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: statistic/message.proto

package system_statistic_

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for SystemSvc service

type SystemSvcService interface {
}

type systemSvcService struct {
	c    client.Client
	name string
}

func NewSystemSvcService(name string, c client.Client) SystemSvcService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "system.statistic"
	}
	return &systemSvcService{
		c:    c,
		name: name,
	}
}

// Server API for SystemSvc service

type SystemSvcHandler interface {
}

func RegisterSystemSvcHandler(s server.Server, hdlr SystemSvcHandler, opts ...server.HandlerOption) error {
	type systemSvc interface {
	}
	type SystemSvc struct {
		systemSvc
	}
	h := &systemSvcHandler{hdlr}
	return s.Handle(s.NewHandler(&SystemSvc{h}, opts...))
}

type systemSvcHandler struct {
	SystemSvcHandler
}
