// Code generated by protoc-gen-go. DO NOT EDIT.
// source: synchonize/message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response struct {
	Status               int32    `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,4,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c6bdf8b0a87c6a, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type ZoneRequest struct {
	Alive                int32    `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	Zones                []*Zone  `protobuf:"bytes,2,rep,name=zones,proto3" json:"zones,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneRequest) Reset()         { *m = ZoneRequest{} }
func (m *ZoneRequest) String() string { return proto.CompactTextString(m) }
func (*ZoneRequest) ProtoMessage()    {}
func (*ZoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c6bdf8b0a87c6a, []int{1}
}

func (m *ZoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneRequest.Unmarshal(m, b)
}
func (m *ZoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneRequest.Marshal(b, m, deterministic)
}
func (m *ZoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneRequest.Merge(m, src)
}
func (m *ZoneRequest) XXX_Size() int {
	return xxx_messageInfo_ZoneRequest.Size(m)
}
func (m *ZoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneRequest proto.InternalMessageInfo

func (m *ZoneRequest) GetAlive() int32 {
	if m != nil {
		return m.Alive
	}
	return 0
}

func (m *ZoneRequest) GetZones() []*Zone {
	if m != nil {
		return m.Zones
	}
	return nil
}

type SceneRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SceneRequest) Reset()         { *m = SceneRequest{} }
func (m *SceneRequest) String() string { return proto.CompactTextString(m) }
func (*SceneRequest) ProtoMessage()    {}
func (*SceneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c6bdf8b0a87c6a, []int{2}
}

func (m *SceneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SceneRequest.Unmarshal(m, b)
}
func (m *SceneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SceneRequest.Marshal(b, m, deterministic)
}
func (m *SceneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SceneRequest.Merge(m, src)
}
func (m *SceneRequest) XXX_Size() int {
	return xxx_messageInfo_SceneRequest.Size(m)
}
func (m *SceneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SceneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SceneRequest proto.InternalMessageInfo

type ScheduleRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScheduleRequest) Reset()         { *m = ScheduleRequest{} }
func (m *ScheduleRequest) String() string { return proto.CompactTextString(m) }
func (*ScheduleRequest) ProtoMessage()    {}
func (*ScheduleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c6bdf8b0a87c6a, []int{3}
}

func (m *ScheduleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScheduleRequest.Unmarshal(m, b)
}
func (m *ScheduleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScheduleRequest.Marshal(b, m, deterministic)
}
func (m *ScheduleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleRequest.Merge(m, src)
}
func (m *ScheduleRequest) XXX_Size() int {
	return xxx_messageInfo_ScheduleRequest.Size(m)
}
func (m *ScheduleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleRequest proto.InternalMessageInfo

type Zone struct {
	Valid                string   `protobuf:"bytes,1,opt,name=valid,proto3" json:"valid,omitempty"`
	ZoneId               int32    `protobuf:"varint,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Active               string   `protobuf:"bytes,3,opt,name=active,proto3" json:"active,omitempty"`
	ZoneType             int32    `protobuf:"varint,4,opt,name=zone_type,json=zoneType,proto3" json:"zone_type,omitempty"`
	ZoneName             string   `protobuf:"bytes,5,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	DevicesInzone        int32    `protobuf:"varint,6,opt,name=devices_inzone,json=devicesInzone,proto3" json:"devices_inzone,omitempty"`
	ParentIndex          int32    `protobuf:"varint,7,opt,name=parent_index,json=parentIndex,proto3" json:"parent_index,omitempty"`
	IconName             string   `protobuf:"bytes,8,opt,name=icon_name,json=iconName,proto3" json:"icon_name,omitempty"`
	ExDevId              string   `protobuf:"bytes,9,opt,name=ex_dev_id,json=exDevId,proto3" json:"ex_dev_id,omitempty"`
	ExZoneId             string   `protobuf:"bytes,10,opt,name=ex_zone_id,json=exZoneId,proto3" json:"ex_zone_id,omitempty"`
	ChildZoneId          string   `protobuf:"bytes,11,opt,name=child_zone_id,json=childZoneId,proto3" json:"child_zone_id,omitempty"`
	SecMode              int32    `protobuf:"varint,12,opt,name=sec_mode,json=secMode,proto3" json:"sec_mode,omitempty"`
	EsTimeout            int32    `protobuf:"varint,13,opt,name=es_timeout,json=esTimeout,proto3" json:"es_timeout,omitempty"`
	EsStatus             int32    `protobuf:"varint,14,opt,name=es_status,json=esStatus,proto3" json:"es_status,omitempty"`
	Operation            string   `protobuf:"bytes,15,opt,name=operation,proto3" json:"operation,omitempty"`
	Dim                  int32    `protobuf:"varint,16,opt,name=dim,proto3" json:"dim,omitempty"`
	HomeSecMode          int32    `protobuf:"varint,17,opt,name=home_sec_mode,json=homeSecMode,proto3" json:"home_sec_mode,omitempty"`
	ZoneSecMode          int32    `protobuf:"varint,18,opt,name=zone_sec_mode,json=zoneSecMode,proto3" json:"zone_sec_mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Zone) Reset()         { *m = Zone{} }
func (m *Zone) String() string { return proto.CompactTextString(m) }
func (*Zone) ProtoMessage()    {}
func (*Zone) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c6bdf8b0a87c6a, []int{4}
}

func (m *Zone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Zone.Unmarshal(m, b)
}
func (m *Zone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Zone.Marshal(b, m, deterministic)
}
func (m *Zone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Zone.Merge(m, src)
}
func (m *Zone) XXX_Size() int {
	return xxx_messageInfo_Zone.Size(m)
}
func (m *Zone) XXX_DiscardUnknown() {
	xxx_messageInfo_Zone.DiscardUnknown(m)
}

var xxx_messageInfo_Zone proto.InternalMessageInfo

func (m *Zone) GetValid() string {
	if m != nil {
		return m.Valid
	}
	return ""
}

func (m *Zone) GetZoneId() int32 {
	if m != nil {
		return m.ZoneId
	}
	return 0
}

func (m *Zone) GetActive() string {
	if m != nil {
		return m.Active
	}
	return ""
}

func (m *Zone) GetZoneType() int32 {
	if m != nil {
		return m.ZoneType
	}
	return 0
}

func (m *Zone) GetZoneName() string {
	if m != nil {
		return m.ZoneName
	}
	return ""
}

func (m *Zone) GetDevicesInzone() int32 {
	if m != nil {
		return m.DevicesInzone
	}
	return 0
}

func (m *Zone) GetParentIndex() int32 {
	if m != nil {
		return m.ParentIndex
	}
	return 0
}

func (m *Zone) GetIconName() string {
	if m != nil {
		return m.IconName
	}
	return ""
}

func (m *Zone) GetExDevId() string {
	if m != nil {
		return m.ExDevId
	}
	return ""
}

func (m *Zone) GetExZoneId() string {
	if m != nil {
		return m.ExZoneId
	}
	return ""
}

func (m *Zone) GetChildZoneId() string {
	if m != nil {
		return m.ChildZoneId
	}
	return ""
}

func (m *Zone) GetSecMode() int32 {
	if m != nil {
		return m.SecMode
	}
	return 0
}

func (m *Zone) GetEsTimeout() int32 {
	if m != nil {
		return m.EsTimeout
	}
	return 0
}

func (m *Zone) GetEsStatus() int32 {
	if m != nil {
		return m.EsStatus
	}
	return 0
}

func (m *Zone) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *Zone) GetDim() int32 {
	if m != nil {
		return m.Dim
	}
	return 0
}

func (m *Zone) GetHomeSecMode() int32 {
	if m != nil {
		return m.HomeSecMode
	}
	return 0
}

func (m *Zone) GetZoneSecMode() int32 {
	if m != nil {
		return m.ZoneSecMode
	}
	return 0
}

type Request struct {
	DevId                int32    `protobuf:"varint,1,opt,name=dev_id,json=devId,proto3" json:"dev_id,omitempty"`
	Reachable            int32    `protobuf:"varint,2,opt,name=reachable,proto3" json:"reachable,omitempty"`
	Active               string   `protobuf:"bytes,3,opt,name=active,proto3" json:"active,omitempty"`
	Mac                  string   `protobuf:"bytes,4,opt,name=mac,proto3" json:"mac,omitempty"`
	DevType              int32    `protobuf:"varint,5,opt,name=dev_type,json=devType,proto3" json:"dev_type,omitempty"`
	SubDevType           int32    `protobuf:"varint,6,opt,name=sub_dev_type,json=subDevType,proto3" json:"sub_dev_type,omitempty"`
	ApplianceType        int32    `protobuf:"varint,7,opt,name=appliance_type,json=applianceType,proto3" json:"appliance_type,omitempty"`
	DevName              string   `protobuf:"bytes,8,opt,name=dev_name,json=devName,proto3" json:"dev_name,omitempty"`
	GatewayMac           string   `protobuf:"bytes,9,opt,name=gatewayMac,proto3" json:"gatewayMac,omitempty"`
	UniqueName           string   `protobuf:"bytes,10,opt,name=uniqueName,proto3" json:"uniqueName,omitempty"`
	Zoneid               int32    `protobuf:"varint,11,opt,name=zoneid,proto3" json:"zoneid,omitempty"`
	Status               *Status  `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c6bdf8b0a87c6a, []int{5}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetDevId() int32 {
	if m != nil {
		return m.DevId
	}
	return 0
}

func (m *Request) GetReachable() int32 {
	if m != nil {
		return m.Reachable
	}
	return 0
}

func (m *Request) GetActive() string {
	if m != nil {
		return m.Active
	}
	return ""
}

func (m *Request) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *Request) GetDevType() int32 {
	if m != nil {
		return m.DevType
	}
	return 0
}

func (m *Request) GetSubDevType() int32 {
	if m != nil {
		return m.SubDevType
	}
	return 0
}

func (m *Request) GetApplianceType() int32 {
	if m != nil {
		return m.ApplianceType
	}
	return 0
}

func (m *Request) GetDevName() string {
	if m != nil {
		return m.DevName
	}
	return ""
}

func (m *Request) GetGatewayMac() string {
	if m != nil {
		return m.GatewayMac
	}
	return ""
}

func (m *Request) GetUniqueName() string {
	if m != nil {
		return m.UniqueName
	}
	return ""
}

func (m *Request) GetZoneid() int32 {
	if m != nil {
		return m.Zoneid
	}
	return 0
}

func (m *Request) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type ChangeGatewayRequest struct {
	// new gateway macaddress
	MacAddress string `protobuf:"bytes,1,opt,name=macAddress,proto3" json:"macAddress,omitempty"`
	// device name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// device mac address
	Serial               string   `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeGatewayRequest) Reset()         { *m = ChangeGatewayRequest{} }
func (m *ChangeGatewayRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeGatewayRequest) ProtoMessage()    {}
func (*ChangeGatewayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c6bdf8b0a87c6a, []int{6}
}

func (m *ChangeGatewayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeGatewayRequest.Unmarshal(m, b)
}
func (m *ChangeGatewayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeGatewayRequest.Marshal(b, m, deterministic)
}
func (m *ChangeGatewayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeGatewayRequest.Merge(m, src)
}
func (m *ChangeGatewayRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeGatewayRequest.Size(m)
}
func (m *ChangeGatewayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeGatewayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeGatewayRequest proto.InternalMessageInfo

func (m *ChangeGatewayRequest) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *ChangeGatewayRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChangeGatewayRequest) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

type Status struct {
	Red                  string   `protobuf:"bytes,1,opt,name=red,proto3" json:"red,omitempty"`
	Green                string   `protobuf:"bytes,2,opt,name=green,proto3" json:"green,omitempty"`
	Blue                 string   `protobuf:"bytes,3,opt,name=blue,proto3" json:"blue,omitempty"`
	Warm                 string   `protobuf:"bytes,4,opt,name=warm,proto3" json:"warm,omitempty"`
	Natural              string   `protobuf:"bytes,5,opt,name=natural,proto3" json:"natural,omitempty"`
	Cool                 string   `protobuf:"bytes,6,opt,name=cool,proto3" json:"cool,omitempty"`
	Dimm                 string   `protobuf:"bytes,7,opt,name=dimm,proto3" json:"dimm,omitempty"`
	SensorSecMode        string   `protobuf:"bytes,8,opt,name=SensorSecMode,proto3" json:"SensorSecMode,omitempty"`
	OpMode               string   `protobuf:"bytes,9,opt,name=opMode,proto3" json:"opMode,omitempty"`
	Sleep                string   `protobuf:"bytes,10,opt,name=sleep,proto3" json:"sleep,omitempty"`
	Onoff                string   `protobuf:"bytes,11,opt,name=onoff,proto3" json:"onoff,omitempty"`
	Light                string   `protobuf:"bytes,12,opt,name=light,proto3" json:"light,omitempty"`
	Utlight              string   `protobuf:"bytes,13,opt,name=utlight,proto3" json:"utlight,omitempty"`
	Ltlight              string   `protobuf:"bytes,14,opt,name=ltlight,proto3" json:"ltlight,omitempty"`
	Temp                 string   `protobuf:"bytes,15,opt,name=temp,proto3" json:"temp,omitempty"`
	Uttemp               string   `protobuf:"bytes,16,opt,name=uttemp,proto3" json:"uttemp,omitempty"`
	Lttemp               string   `protobuf:"bytes,17,opt,name=lttemp,proto3" json:"lttemp,omitempty"`
	Motion               string   `protobuf:"bytes,18,opt,name=motion,proto3" json:"motion,omitempty"`
	Enmotion             string   `protobuf:"bytes,19,opt,name=enmotion,proto3" json:"enmotion,omitempty"`
	Motiontimeout        string   `protobuf:"bytes,20,opt,name=motiontimeout,proto3" json:"motiontimeout,omitempty"`
	Slider               string   `protobuf:"bytes,21,opt,name=slider,proto3" json:"slider,omitempty"`
	Ulslider             string   `protobuf:"bytes,22,opt,name=ulslider,proto3" json:"ulslider,omitempty"`
	Llslider             string   `protobuf:"bytes,23,opt,name=llslider,proto3" json:"llslider,omitempty"`
	Humidity             string   `protobuf:"bytes,24,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Uhumidity            string   `protobuf:"bytes,25,opt,name=uhumidity,proto3" json:"uhumidity,omitempty"`
	Lhumidity            string   `protobuf:"bytes,26,opt,name=lhumidity,proto3" json:"lhumidity,omitempty"`
	Sonoff               string   `protobuf:"bytes,27,opt,name=sonoff,proto3" json:"sonoff,omitempty"`
	Ledstatusen          string   `protobuf:"bytes,28,opt,name=ledstatusen,proto3" json:"ledstatusen,omitempty"`
	MConfig              string   `protobuf:"bytes,29,opt,name=mConfig,proto3" json:"mConfig,omitempty"`
	MVal                 string   `protobuf:"bytes,30,opt,name=mVal,proto3" json:"mVal,omitempty"`
	DhtTemp              string   `protobuf:"bytes,31,opt,name=dht_temp,json=dhtTemp,proto3" json:"dht_temp,omitempty"`
	DhtHumidity          string   `protobuf:"bytes,32,opt,name=dht_humidity,json=dhtHumidity,proto3" json:"dht_humidity,omitempty"`
	Plug_1               string   `protobuf:"bytes,34,opt,name=plug_1,json=plug1,proto3" json:"plug_1,omitempty"`
	Current_1            string   `protobuf:"bytes,35,opt,name=current_1,json=current1,proto3" json:"current_1,omitempty"`
	Voltage_1            string   `protobuf:"bytes,36,opt,name=voltage_1,json=voltage1,proto3" json:"voltage_1,omitempty"`
	Power_1              string   `protobuf:"bytes,37,opt,name=power_1,json=power1,proto3" json:"power_1,omitempty"`
	Plug_2               string   `protobuf:"bytes,38,opt,name=plug_2,json=plug2,proto3" json:"plug_2,omitempty"`
	Current_2            string   `protobuf:"bytes,39,opt,name=current_2,json=current2,proto3" json:"current_2,omitempty"`
	Voltage_2            string   `protobuf:"bytes,40,opt,name=voltage_2,json=voltage2,proto3" json:"voltage_2,omitempty"`
	Power_2              string   `protobuf:"bytes,41,opt,name=power_2,json=power2,proto3" json:"power_2,omitempty"`
	SlightOnoff          string   `protobuf:"bytes,42,opt,name=slight_onoff,json=slightOnoff,proto3" json:"slight_onoff,omitempty"`
	SlightSw_1           string   `protobuf:"bytes,43,opt,name=slight_sw_1,json=slightSw1,proto3" json:"slight_sw_1,omitempty"`
	SlightSw_2           string   `protobuf:"bytes,44,opt,name=slight_sw_2,json=slightSw2,proto3" json:"slight_sw_2,omitempty"`
	Slight_1             string   `protobuf:"bytes,45,opt,name=slight_1,json=slight1,proto3" json:"slight_1,omitempty"`
	Slight_2             string   `protobuf:"bytes,46,opt,name=slight_2,json=slight2,proto3" json:"slight_2,omitempty"`
	Slight_3             string   `protobuf:"bytes,47,opt,name=slight_3,json=slight3,proto3" json:"slight_3,omitempty"`
	Slight_4             string   `protobuf:"bytes,48,opt,name=slight_4,json=slight4,proto3" json:"slight_4,omitempty"`
	SlightSw_1Name       string   `protobuf:"bytes,49,opt,name=slight_sw_1_name,json=slightSw1Name,proto3" json:"slight_sw_1_name,omitempty"`
	SlightSw_2Name       string   `protobuf:"bytes,50,opt,name=slight_sw_2_name,json=slightSw2Name,proto3" json:"slight_sw_2_name,omitempty"`
	SlightName_1         string   `protobuf:"bytes,51,opt,name=slight_name_1,json=slightName1,proto3" json:"slight_name_1,omitempty"`
	SlightName_2         string   `protobuf:"bytes,52,opt,name=slight_name_2,json=slightName2,proto3" json:"slight_name_2,omitempty"`
	SlightName_3         string   `protobuf:"bytes,53,opt,name=slight_name_3,json=slightName3,proto3" json:"slight_name_3,omitempty"`
	SlightName_4         string   `protobuf:"bytes,54,opt,name=slight_name_4,json=slightName4,proto3" json:"slight_name_4,omitempty"`
	Secmode              string   `protobuf:"bytes,66,opt,name=secmode,proto3" json:"secmode,omitempty"`
	Motionhwpresent      string   `protobuf:"bytes,67,opt,name=motionhwpresent,proto3" json:"motionhwpresent,omitempty"`
	TpsMotion            string   `protobuf:"bytes,75,opt,name=tps_motion,json=tpsMotion,proto3" json:"tps_motion,omitempty"`
	TpsDoorlock          string   `protobuf:"bytes,76,opt,name=tps_doorlock,json=tpsDoorlock,proto3" json:"tps_doorlock,omitempty"`
	TpsCo                string   `protobuf:"bytes,77,opt,name=tps_co,json=tpsCo,proto3" json:"tps_co,omitempty"`
	TpsSmoke             string   `protobuf:"bytes,78,opt,name=tps_smoke,json=tpsSmoke,proto3" json:"tps_smoke,omitempty"`
	TpsAlarm1            string   `protobuf:"bytes,79,opt,name=tps_alarm1,json=tpsAlarm1,proto3" json:"tps_alarm1,omitempty"`
	TpsAlarm2            string   `protobuf:"bytes,80,opt,name=tps_alarm2,json=tpsAlarm2,proto3" json:"tps_alarm2,omitempty"`
	TpsTamper            string   `protobuf:"bytes,81,opt,name=tps_tamper,json=tpsTamper,proto3" json:"tps_tamper,omitempty"`
	TpsBattery           string   `protobuf:"bytes,82,opt,name=tps_battery,json=tpsBattery,proto3" json:"tps_battery,omitempty"`
	TpsSecm              string   `protobuf:"bytes,83,opt,name=tps_secm,json=tpsSecm,proto3" json:"tps_secm,omitempty"`
	TpiRev1              string   `protobuf:"bytes,84,opt,name=tpi_rev1,json=tpiRev1,proto3" json:"tpi_rev1,omitempty"`
	TpiSecm              string   `protobuf:"bytes,85,opt,name=tpi_secm,json=tpiSecm,proto3" json:"tpi_secm,omitempty"`
	Onoff_2              string   `protobuf:"bytes,86,opt,name=onoff_2,json=onoff2,proto3" json:"onoff_2,omitempty"`
	Onoff_3              string   `protobuf:"bytes,87,opt,name=onoff_3,json=onoff3,proto3" json:"onoff_3,omitempty"`
	GvswitchSw_1Name     string   `protobuf:"bytes,88,opt,name=gvswitch_sw_1_name,json=gvswitchSw1Name,proto3" json:"gvswitch_sw_1_name,omitempty"`
	GvswitchSw_2Name     string   `protobuf:"bytes,89,opt,name=gvswitch_sw_2_name,json=gvswitchSw2Name,proto3" json:"gvswitch_sw_2_name,omitempty"`
	GvswitchSw_3Name     string   `protobuf:"bytes,90,opt,name=gvswitch_sw_3_name,json=gvswitchSw3Name,proto3" json:"gvswitch_sw_3_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c6bdf8b0a87c6a, []int{7}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetRed() string {
	if m != nil {
		return m.Red
	}
	return ""
}

func (m *Status) GetGreen() string {
	if m != nil {
		return m.Green
	}
	return ""
}

func (m *Status) GetBlue() string {
	if m != nil {
		return m.Blue
	}
	return ""
}

func (m *Status) GetWarm() string {
	if m != nil {
		return m.Warm
	}
	return ""
}

func (m *Status) GetNatural() string {
	if m != nil {
		return m.Natural
	}
	return ""
}

func (m *Status) GetCool() string {
	if m != nil {
		return m.Cool
	}
	return ""
}

func (m *Status) GetDimm() string {
	if m != nil {
		return m.Dimm
	}
	return ""
}

func (m *Status) GetSensorSecMode() string {
	if m != nil {
		return m.SensorSecMode
	}
	return ""
}

func (m *Status) GetOpMode() string {
	if m != nil {
		return m.OpMode
	}
	return ""
}

func (m *Status) GetSleep() string {
	if m != nil {
		return m.Sleep
	}
	return ""
}

func (m *Status) GetOnoff() string {
	if m != nil {
		return m.Onoff
	}
	return ""
}

func (m *Status) GetLight() string {
	if m != nil {
		return m.Light
	}
	return ""
}

func (m *Status) GetUtlight() string {
	if m != nil {
		return m.Utlight
	}
	return ""
}

func (m *Status) GetLtlight() string {
	if m != nil {
		return m.Ltlight
	}
	return ""
}

func (m *Status) GetTemp() string {
	if m != nil {
		return m.Temp
	}
	return ""
}

func (m *Status) GetUttemp() string {
	if m != nil {
		return m.Uttemp
	}
	return ""
}

func (m *Status) GetLttemp() string {
	if m != nil {
		return m.Lttemp
	}
	return ""
}

func (m *Status) GetMotion() string {
	if m != nil {
		return m.Motion
	}
	return ""
}

func (m *Status) GetEnmotion() string {
	if m != nil {
		return m.Enmotion
	}
	return ""
}

func (m *Status) GetMotiontimeout() string {
	if m != nil {
		return m.Motiontimeout
	}
	return ""
}

func (m *Status) GetSlider() string {
	if m != nil {
		return m.Slider
	}
	return ""
}

func (m *Status) GetUlslider() string {
	if m != nil {
		return m.Ulslider
	}
	return ""
}

func (m *Status) GetLlslider() string {
	if m != nil {
		return m.Llslider
	}
	return ""
}

func (m *Status) GetHumidity() string {
	if m != nil {
		return m.Humidity
	}
	return ""
}

func (m *Status) GetUhumidity() string {
	if m != nil {
		return m.Uhumidity
	}
	return ""
}

func (m *Status) GetLhumidity() string {
	if m != nil {
		return m.Lhumidity
	}
	return ""
}

func (m *Status) GetSonoff() string {
	if m != nil {
		return m.Sonoff
	}
	return ""
}

func (m *Status) GetLedstatusen() string {
	if m != nil {
		return m.Ledstatusen
	}
	return ""
}

func (m *Status) GetMConfig() string {
	if m != nil {
		return m.MConfig
	}
	return ""
}

func (m *Status) GetMVal() string {
	if m != nil {
		return m.MVal
	}
	return ""
}

func (m *Status) GetDhtTemp() string {
	if m != nil {
		return m.DhtTemp
	}
	return ""
}

func (m *Status) GetDhtHumidity() string {
	if m != nil {
		return m.DhtHumidity
	}
	return ""
}

func (m *Status) GetPlug_1() string {
	if m != nil {
		return m.Plug_1
	}
	return ""
}

func (m *Status) GetCurrent_1() string {
	if m != nil {
		return m.Current_1
	}
	return ""
}

func (m *Status) GetVoltage_1() string {
	if m != nil {
		return m.Voltage_1
	}
	return ""
}

func (m *Status) GetPower_1() string {
	if m != nil {
		return m.Power_1
	}
	return ""
}

func (m *Status) GetPlug_2() string {
	if m != nil {
		return m.Plug_2
	}
	return ""
}

func (m *Status) GetCurrent_2() string {
	if m != nil {
		return m.Current_2
	}
	return ""
}

func (m *Status) GetVoltage_2() string {
	if m != nil {
		return m.Voltage_2
	}
	return ""
}

func (m *Status) GetPower_2() string {
	if m != nil {
		return m.Power_2
	}
	return ""
}

func (m *Status) GetSlightOnoff() string {
	if m != nil {
		return m.SlightOnoff
	}
	return ""
}

func (m *Status) GetSlightSw_1() string {
	if m != nil {
		return m.SlightSw_1
	}
	return ""
}

func (m *Status) GetSlightSw_2() string {
	if m != nil {
		return m.SlightSw_2
	}
	return ""
}

func (m *Status) GetSlight_1() string {
	if m != nil {
		return m.Slight_1
	}
	return ""
}

func (m *Status) GetSlight_2() string {
	if m != nil {
		return m.Slight_2
	}
	return ""
}

func (m *Status) GetSlight_3() string {
	if m != nil {
		return m.Slight_3
	}
	return ""
}

func (m *Status) GetSlight_4() string {
	if m != nil {
		return m.Slight_4
	}
	return ""
}

func (m *Status) GetSlightSw_1Name() string {
	if m != nil {
		return m.SlightSw_1Name
	}
	return ""
}

func (m *Status) GetSlightSw_2Name() string {
	if m != nil {
		return m.SlightSw_2Name
	}
	return ""
}

func (m *Status) GetSlightName_1() string {
	if m != nil {
		return m.SlightName_1
	}
	return ""
}

func (m *Status) GetSlightName_2() string {
	if m != nil {
		return m.SlightName_2
	}
	return ""
}

func (m *Status) GetSlightName_3() string {
	if m != nil {
		return m.SlightName_3
	}
	return ""
}

func (m *Status) GetSlightName_4() string {
	if m != nil {
		return m.SlightName_4
	}
	return ""
}

func (m *Status) GetSecmode() string {
	if m != nil {
		return m.Secmode
	}
	return ""
}

func (m *Status) GetMotionhwpresent() string {
	if m != nil {
		return m.Motionhwpresent
	}
	return ""
}

func (m *Status) GetTpsMotion() string {
	if m != nil {
		return m.TpsMotion
	}
	return ""
}

func (m *Status) GetTpsDoorlock() string {
	if m != nil {
		return m.TpsDoorlock
	}
	return ""
}

func (m *Status) GetTpsCo() string {
	if m != nil {
		return m.TpsCo
	}
	return ""
}

func (m *Status) GetTpsSmoke() string {
	if m != nil {
		return m.TpsSmoke
	}
	return ""
}

func (m *Status) GetTpsAlarm1() string {
	if m != nil {
		return m.TpsAlarm1
	}
	return ""
}

func (m *Status) GetTpsAlarm2() string {
	if m != nil {
		return m.TpsAlarm2
	}
	return ""
}

func (m *Status) GetTpsTamper() string {
	if m != nil {
		return m.TpsTamper
	}
	return ""
}

func (m *Status) GetTpsBattery() string {
	if m != nil {
		return m.TpsBattery
	}
	return ""
}

func (m *Status) GetTpsSecm() string {
	if m != nil {
		return m.TpsSecm
	}
	return ""
}

func (m *Status) GetTpiRev1() string {
	if m != nil {
		return m.TpiRev1
	}
	return ""
}

func (m *Status) GetTpiSecm() string {
	if m != nil {
		return m.TpiSecm
	}
	return ""
}

func (m *Status) GetOnoff_2() string {
	if m != nil {
		return m.Onoff_2
	}
	return ""
}

func (m *Status) GetOnoff_3() string {
	if m != nil {
		return m.Onoff_3
	}
	return ""
}

func (m *Status) GetGvswitchSw_1Name() string {
	if m != nil {
		return m.GvswitchSw_1Name
	}
	return ""
}

func (m *Status) GetGvswitchSw_2Name() string {
	if m != nil {
		return m.GvswitchSw_2Name
	}
	return ""
}

func (m *Status) GetGvswitchSw_3Name() string {
	if m != nil {
		return m.GvswitchSw_3Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*ZoneRequest)(nil), "ZoneRequest")
	proto.RegisterType((*SceneRequest)(nil), "SceneRequest")
	proto.RegisterType((*ScheduleRequest)(nil), "ScheduleRequest")
	proto.RegisterType((*Zone)(nil), "Zone")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*ChangeGatewayRequest)(nil), "ChangeGatewayRequest")
	proto.RegisterType((*Status)(nil), "Status")
}

func init() { proto.RegisterFile("synchonize/message.proto", fileDescriptor_32c6bdf8b0a87c6a) }

var fileDescriptor_32c6bdf8b0a87c6a = []byte{
	// 1519 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x57, 0xe1, 0x76, 0xd3, 0xc6,
	0x12, 0x3e, 0x24, 0x71, 0x12, 0x6f, 0xec, 0x10, 0x74, 0x09, 0x2c, 0x01, 0x92, 0x60, 0xc8, 0x25,
	0xf7, 0x72, 0xaf, 0xa9, 0xe4, 0xb4, 0xbf, 0x0b, 0x49, 0x4f, 0x9b, 0xd3, 0x06, 0x5a, 0x3b, 0xa5,
	0x2d, 0x7f, 0x54, 0x45, 0x1a, 0x6c, 0x1d, 0x24, 0xad, 0xd0, 0xae, 0xec, 0x84, 0x7f, 0x7d, 0x8e,
	0xbe, 0x40, 0x1f, 0xab, 0x8f, 0xd2, 0x33, 0x33, 0x2b, 0x45, 0xf6, 0xa1, 0xa7, 0xff, 0x76, 0xbe,
	0xef, 0xdb, 0x9d, 0xd9, 0x99, 0xd9, 0x95, 0x56, 0x48, 0x7d, 0x95, 0x85, 0x13, 0x95, 0xc5, 0x1f,
	0xe1, 0x79, 0x0a, 0x5a, 0x07, 0x63, 0xe8, 0xe7, 0x85, 0x32, 0xaa, 0xf7, 0xab, 0x58, 0x1f, 0x82,
	0xce, 0x55, 0xa6, 0xc1, 0xb9, 0x23, 0x56, 0x47, 0x26, 0x30, 0xa5, 0x96, 0x37, 0xf6, 0x6f, 0x1c,
	0xb6, 0x86, 0xd6, 0x72, 0xa4, 0x58, 0x3b, 0xe3, 0x49, 0x72, 0x69, 0xff, 0xc6, 0x61, 0x7b, 0x58,
	0x99, 0x4e, 0x4f, 0x74, 0xbe, 0x2a, 0x0a, 0x55, 0x54, 0xf4, 0x0a, 0xd1, 0x73, 0x58, 0xef, 0x4b,
	0xb1, 0xf1, 0x56, 0x65, 0x30, 0x84, 0x0f, 0x25, 0x68, 0xe3, 0xdc, 0x16, 0xad, 0x20, 0x89, 0xa7,
	0x60, 0x7d, 0xb0, 0xe1, 0xdc, 0x17, 0xad, 0x8f, 0x2a, 0x03, 0x2d, 0x97, 0xf6, 0x97, 0x0f, 0x37,
	0xbc, 0x56, 0x9f, 0xa6, 0x30, 0xd6, 0xdb, 0x14, 0x9d, 0x51, 0x08, 0xf5, 0x12, 0xbd, 0x5b, 0xe2,
	0xe6, 0x28, 0x9c, 0x40, 0x54, 0x26, 0x35, 0xf4, 0xfb, 0x8a, 0x58, 0xc1, 0x29, 0xb8, 0xfc, 0x34,
	0x48, 0xe2, 0x88, 0x96, 0x6f, 0x0f, 0xd9, 0x70, 0xee, 0x8a, 0x35, 0x5c, 0xca, 0x8f, 0x23, 0xda,
	0x41, 0x6b, 0xb8, 0x8a, 0xe6, 0x69, 0x84, 0x5b, 0x0e, 0x42, 0x83, 0xe1, 0x2c, 0x93, 0xde, 0x5a,
	0xce, 0x7d, 0xd1, 0xa6, 0x09, 0xe6, 0x2a, 0xe7, 0x5d, 0xb5, 0x86, 0xeb, 0x08, 0x9c, 0x5f, 0xe5,
	0xd7, 0x64, 0x16, 0xa4, 0x20, 0x5b, 0x34, 0x8f, 0xc8, 0x57, 0x41, 0x0a, 0xce, 0x81, 0xd8, 0x8c,
	0x60, 0x1a, 0x87, 0xa0, 0xfd, 0x38, 0x43, 0x54, 0xae, 0xd2, 0xf4, 0xae, 0x45, 0x4f, 0x09, 0x74,
	0x1e, 0x89, 0x4e, 0x1e, 0x14, 0x90, 0x19, 0x3f, 0xce, 0x22, 0xb8, 0x94, 0x6b, 0x24, 0xda, 0x60,
	0xec, 0x14, 0x21, 0x74, 0x13, 0x87, 0x2a, 0x63, 0x37, 0xeb, 0xec, 0x06, 0x01, 0x72, 0xb3, 0x23,
	0xda, 0x70, 0xe9, 0x47, 0x30, 0xc5, 0x3d, 0xb5, 0xb9, 0x2a, 0x70, 0x79, 0x02, 0xd3, 0xd3, 0xc8,
	0x79, 0x20, 0x04, 0x5c, 0xfa, 0xd5, 0x86, 0x05, 0xcf, 0x84, 0xcb, 0xb7, 0xbc, 0xe5, 0x9e, 0xe8,
	0x86, 0x93, 0x38, 0x89, 0x6a, 0xc1, 0x06, 0x09, 0x36, 0x08, 0xb4, 0x9a, 0x7b, 0x62, 0x5d, 0x43,
	0xe8, 0xa7, 0x2a, 0x02, 0xd9, 0xa1, 0xc8, 0xd6, 0x34, 0x84, 0x67, 0x2a, 0x02, 0xe7, 0xa1, 0x10,
	0xa0, 0x7d, 0x13, 0xa7, 0xa0, 0x4a, 0x23, 0xbb, 0x44, 0xb6, 0x41, 0x9f, 0x33, 0x80, 0x41, 0x83,
	0xf6, 0x35, 0xb7, 0xd1, 0x26, 0x27, 0x0e, 0xb4, 0x6d, 0xa4, 0x07, 0xa2, 0xad, 0x72, 0x28, 0x02,
	0x13, 0xab, 0x4c, 0xde, 0x24, 0xb7, 0xd7, 0x80, 0xb3, 0x25, 0x96, 0xa3, 0x38, 0x95, 0x5b, 0x34,
	0x09, 0x87, 0x18, 0xea, 0x44, 0xa5, 0xe0, 0xd7, 0xb1, 0xdc, 0xe2, 0x2c, 0x21, 0x38, 0xb2, 0xf1,
	0xf4, 0x44, 0x97, 0x36, 0x52, 0x6b, 0x1c, 0xd6, 0x20, 0x68, 0x35, 0xbd, 0x3f, 0x97, 0xc4, 0x5a,
	0xd5, 0x7f, 0xdb, 0x62, 0xd5, 0x66, 0xcd, 0x36, 0x60, 0x64, 0x73, 0xd6, 0x2e, 0x20, 0x08, 0x27,
	0xc1, 0x45, 0x02, 0xb6, 0x47, 0xae, 0x81, 0xbf, 0x6d, 0x93, 0x2d, 0xb1, 0x9c, 0x06, 0xa1, 0x6d,
	0x7b, 0x1c, 0x62, 0xe6, 0x70, 0x79, 0xea, 0x9b, 0x16, 0x67, 0x2e, 0x82, 0x29, 0xb5, 0xcd, 0xbe,
	0xe8, 0xe8, 0xf2, 0xc2, 0xaf, 0x69, 0xee, 0x0b, 0xa1, 0xcb, 0x8b, 0x13, 0xab, 0x38, 0x10, 0x9b,
	0x41, 0x9e, 0x27, 0x71, 0x90, 0x85, 0xb6, 0xf5, 0xb8, 0x2d, 0xba, 0x35, 0x4a, 0x32, 0xeb, 0xa3,
	0xd1, 0x17, 0xe8, 0x83, 0xda, 0x62, 0x57, 0x88, 0x71, 0x60, 0x60, 0x16, 0x5c, 0x9d, 0x05, 0xa1,
	0xed, 0x8b, 0x06, 0x82, 0x7c, 0x99, 0xc5, 0x1f, 0x4a, 0xea, 0x55, 0xdb, 0x1a, 0x0d, 0x04, 0x37,
	0x8a, 0x89, 0xb3, 0x5d, 0x61, 0xcf, 0x49, 0x1c, 0x39, 0x7b, 0x62, 0xd5, 0xd6, 0x14, 0xdb, 0x61,
	0xc3, 0x5b, 0xeb, 0x73, 0x49, 0x87, 0x16, 0xee, 0x5d, 0x88, 0xdb, 0xc7, 0x93, 0x20, 0x1b, 0xc3,
	0xd7, 0xec, 0xac, 0x4a, 0xf7, 0xae, 0x10, 0x69, 0x10, 0xbe, 0x88, 0xa2, 0x02, 0xb4, 0xb6, 0x87,
	0xb2, 0x81, 0x38, 0x8e, 0x58, 0xa1, 0x7d, 0xf0, 0xc5, 0x42, 0x63, 0x0c, 0x42, 0x43, 0x11, 0x07,
	0x49, 0x95, 0x6d, 0xb6, 0x7a, 0xbf, 0x6d, 0x55, 0x17, 0x14, 0x26, 0xbe, 0x80, 0xea, 0x90, 0xe3,
	0x10, 0x0f, 0xfe, 0xb8, 0x00, 0xc8, 0xec, 0x4a, 0x6c, 0xe0, 0xf2, 0x17, 0x49, 0x59, 0x95, 0x8d,
	0xc6, 0x88, 0xcd, 0x82, 0x22, 0xb5, 0x55, 0xa3, 0x31, 0x5e, 0x71, 0x59, 0x60, 0xca, 0x22, 0x48,
	0xec, 0x81, 0xae, 0x4c, 0x54, 0x87, 0x4a, 0x25, 0x54, 0xad, 0xf6, 0x90, 0xc6, 0x88, 0x45, 0x71,
	0x9a, 0x52, 0x75, 0xda, 0x43, 0x1a, 0x3b, 0x4f, 0x44, 0x77, 0x04, 0x99, 0x56, 0x85, 0x6d, 0x3a,
	0x5b, 0x99, 0x79, 0x10, 0xb7, 0xa6, 0x72, 0xa2, 0xb9, 0x36, 0xd6, 0xc2, 0xe8, 0x75, 0x02, 0x90,
	0xdb, 0x92, 0xb0, 0x81, 0xa8, 0xca, 0xd4, 0xbb, 0x77, 0xf6, 0x88, 0xb2, 0x81, 0x68, 0x12, 0x8f,
	0x27, 0x86, 0x4a, 0xd1, 0x1e, 0xb2, 0x81, 0x3b, 0x28, 0x0d, 0xe3, 0x5d, 0xde, 0x81, 0x35, 0x91,
	0x49, 0x2c, 0xb3, 0xc9, 0x8c, 0x35, 0x71, 0x1f, 0x06, 0xd2, 0xdc, 0x1e, 0x45, 0x1a, 0x63, 0x84,
	0xa5, 0x21, 0x74, 0x8b, 0x23, 0x64, 0x0b, 0xf1, 0x84, 0xf1, 0x5b, 0x8c, 0x27, 0x35, 0x9e, 0x2a,
	0x3a, 0xd0, 0x0e, 0xe3, 0x6c, 0x39, 0x3b, 0x62, 0x1d, 0x32, 0xcb, 0xfc, 0xcb, 0x5e, 0x41, 0xd6,
	0xc6, 0x5c, 0xf1, 0xa8, 0xba, 0x46, 0x6e, 0x73, 0xae, 0xe6, 0x40, 0x6a, 0x83, 0x24, 0x8e, 0xa0,
	0x90, 0xdb, 0xb6, 0x0d, 0xc8, 0xc2, 0x95, 0xcb, 0xc4, 0x32, 0x77, 0x78, 0xe5, 0xca, 0x46, 0x2e,
	0xa9, 0xb8, 0xbb, 0xcc, 0x25, 0x0d, 0x6e, 0x52, 0xa6, 0x71, 0x14, 0x9b, 0x2b, 0x29, 0x99, 0xab,
	0x6c, 0x3c, 0xfe, 0x65, 0x4d, 0xde, 0xe3, 0x9b, 0xa9, 0x6c, 0xb2, 0x49, 0xcd, 0xee, 0x30, 0x5b,
	0x03, 0x14, 0x27, 0x97, 0xe9, 0xbe, 0x8d, 0x93, 0xeb, 0xb4, 0x2f, 0x36, 0x12, 0x88, 0xf8, 0x7c,
	0x40, 0x26, 0x1f, 0xf0, 0x35, 0xdb, 0x80, 0xb0, 0x32, 0xe9, 0xb1, 0xca, 0xde, 0xc5, 0x63, 0xf9,
	0x90, 0x2b, 0x63, 0x4d, 0xac, 0x4c, 0xfa, 0x26, 0x48, 0xe4, 0x2e, 0x57, 0x06, 0xc7, 0x74, 0xec,
	0x27, 0xc6, 0xa7, 0x1a, 0xec, 0xd9, 0x63, 0x3f, 0x31, 0xe7, 0x58, 0x84, 0x47, 0xa2, 0x83, 0x54,
	0x1d, 0xe3, 0x3e, 0xfb, 0x8a, 0x26, 0xe6, 0x9b, 0x2a, 0xca, 0x6d, 0xb1, 0x9a, 0x27, 0xe5, 0xd8,
	0x77, 0x65, 0x8f, 0xdb, 0x06, 0x2d, 0x17, 0xef, 0xeb, 0xb0, 0x2c, 0xe8, 0x43, 0xe4, 0xca, 0xc7,
	0x9c, 0x15, 0x0b, 0x10, 0x39, 0x55, 0x89, 0x09, 0xc6, 0xe0, 0xbb, 0xf2, 0x09, 0x93, 0x16, 0x70,
	0xf1, 0x9b, 0x9a, 0xab, 0x19, 0x14, 0xbe, 0x2b, 0x0f, 0x78, 0xdf, 0x64, 0xba, 0xb5, 0x27, 0x4f,
	0xfe, 0xfb, 0xda, 0x93, 0xd7, 0xf4, 0xe4, 0xc9, 0xa7, 0x73, 0x9e, 0xbc, 0xa6, 0x27, 0x4f, 0x1e,
	0xce, 0x79, 0xf2, 0xae, 0x3d, 0x79, 0xf2, 0x3f, 0x0d, 0x4f, 0x1e, 0x6e, 0x5b, 0x53, 0x27, 0xfb,
	0x9c, 0xff, 0xff, 0xf2, 0xb6, 0x19, 0x7b, 0x4d, 0x45, 0xd8, 0x15, 0xd6, 0xf4, 0xf5, 0xcc, 0x77,
	0xe5, 0x33, 0x2e, 0x1e, 0x43, 0xa3, 0x99, 0x3b, 0xcf, 0x7b, 0xf2, 0x7f, 0xf3, 0xbc, 0x47, 0x5f,
	0x42, 0xe6, 0x5d, 0xf9, 0x7f, 0x4e, 0x3a, 0xdb, 0x6e, 0x83, 0xf2, 0x64, 0xbf, 0x49, 0x35, 0x67,
	0x0d, 0xe4, 0xf3, 0x26, 0x35, 0x68, 0x50, 0x47, 0xf2, 0xb3, 0x26, 0x75, 0xe4, 0x3c, 0x15, 0x5b,
	0x8d, 0x58, 0xf9, 0x7e, 0x77, 0xf9, 0x64, 0xd4, 0x01, 0xd3, 0x2d, 0x3d, 0x27, 0xf4, 0x58, 0xe8,
	0xcd, 0x0b, 0x3d, 0x12, 0xf6, 0x84, 0x05, 0x48, 0xe3, 0xbb, 0x72, 0xd0, 0xcc, 0x10, 0x4a, 0xdc,
	0x45, 0x8d, 0x27, 0x8f, 0x16, 0x35, 0xde, 0xa2, 0x66, 0x20, 0x3f, 0x5f, 0xd4, 0x0c, 0x16, 0x35,
	0x47, 0xf2, 0x8b, 0x45, 0xcd, 0x11, 0x36, 0xbc, 0x86, 0x90, 0x3e, 0xd3, 0x2f, 0xed, 0xde, 0xd9,
	0x74, 0x0e, 0xc5, 0x4d, 0x3e, 0xfd, 0x93, 0x59, 0x5e, 0x80, 0x86, 0xcc, 0xc8, 0x63, 0x52, 0x2c,
	0xc2, 0xf8, 0x03, 0x62, 0x72, 0xed, 0xdb, 0xab, 0xe5, 0x5b, 0x2e, 0x98, 0xc9, 0xf5, 0x19, 0xdf,
	0x2d, 0x8f, 0x44, 0x07, 0xe9, 0x48, 0xa9, 0x22, 0x51, 0xe1, 0x7b, 0xf9, 0x1d, 0x47, 0x61, 0x72,
	0x7d, 0x62, 0x21, 0x6c, 0x50, 0x94, 0x84, 0x4a, 0x9e, 0x71, 0x83, 0x9a, 0x5c, 0x1f, 0x2b, 0xec,
	0x41, 0x84, 0x75, 0xaa, 0xde, 0x83, 0x7c, 0xc5, 0x3d, 0x68, 0x72, 0x3d, 0x42, 0xbb, 0xf2, 0x1a,
	0x24, 0x41, 0x91, 0xba, 0xf2, 0x75, 0xed, 0xf5, 0x05, 0x01, 0x73, 0xb4, 0x27, 0xbf, 0x9f, 0xa7,
	0xbd, 0x8a, 0x36, 0x41, 0x9a, 0x43, 0x21, 0x7f, 0xa8, 0xe9, 0x73, 0x02, 0x9c, 0x3d, 0x81, 0xf1,
	0xf9, 0x17, 0x81, 0x31, 0x50, 0x5c, 0xc9, 0x21, 0x7f, 0x25, 0x4d, 0xae, 0x5f, 0x32, 0x82, 0x4d,
	0x43, 0xa1, 0x41, 0x98, 0xca, 0x11, 0x27, 0x0e, 0x23, 0x83, 0x30, 0x65, 0x2a, 0xf6, 0x0b, 0x98,
	0xba, 0xf2, 0xbc, 0xa2, 0xe2, 0x21, 0x4c, 0xdd, 0x8a, 0xa2, 0x59, 0x3f, 0xd6, 0x14, 0xcd, 0xba,
	0x2b, 0xd6, 0xe8, 0xc8, 0xf8, 0x9e, 0x7c, 0x63, 0x3f, 0x44, 0x68, 0x7a, 0xd7, 0xc4, 0x40, 0xfe,
	0xd4, 0x20, 0x06, 0xce, 0x33, 0xe1, 0x8c, 0xa7, 0x7a, 0x16, 0x9b, 0x70, 0xd2, 0x68, 0xcf, 0x9f,
	0xb9, 0x46, 0x15, 0x53, 0x35, 0xe8, 0x82, 0xd8, 0xb6, 0xe8, 0x2f, 0x8b, 0x62, 0xef, 0x53, 0xe2,
	0x01, 0x8b, 0xdf, 0x2e, 0x8a, 0x07, 0xd4, 0x8a, 0x7f, 0x2c, 0x89, 0xee, 0xa8, 0x7e, 0xcc, 0x8c,
	0xa6, 0xa1, 0xb3, 0x87, 0x2f, 0x98, 0x71, 0xac, 0x0d, 0x14, 0xce, 0x7a, 0xdf, 0xfe, 0x77, 0xec,
	0xb4, 0xfb, 0xf5, 0xb3, 0xc6, 0x15, 0xdd, 0xb9, 0x5f, 0x13, 0x67, 0xbb, 0xff, 0xa9, 0x5f, 0x95,
	0xe6, 0x94, 0x03, 0xb1, 0x79, 0x9a, 0xf1, 0x3f, 0xde, 0x09, 0xfd, 0xb6, 0x7f, 0x7a, 0xe5, 0xc7,
	0xa2, 0x33, 0x84, 0x54, 0xfd, 0x93, 0x68, 0x1d, 0xff, 0xaa, 0x31, 0x68, 0xa7, 0xd3, 0x6f, 0x3c,
	0x85, 0xe6, 0x1d, 0xb6, 0xe9, 0x89, 0x43, 0xaa, 0x6e, 0xbf, 0xf9, 0xdc, 0x69, 0xca, 0x9e, 0xe1,
	0x4b, 0x88, 0x5f, 0x3e, 0xa4, 0xdc, 0xea, 0x2f, 0x3c, 0x84, 0x1a, 0xe2, 0x8b, 0x55, 0x7a, 0xe1,
	0x0d, 0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xed, 0x3c, 0x3e, 0x4b, 0xfd, 0x0d, 0x00, 0x00,
}
