// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calling.proto

package calling

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NotificationRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationRequest) Reset()         { *m = NotificationRequest{} }
func (m *NotificationRequest) String() string { return proto.CompactTextString(m) }
func (*NotificationRequest) ProtoMessage()    {}
func (*NotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7388c87427bba644, []int{0}
}

func (m *NotificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationRequest.Unmarshal(m, b)
}
func (m *NotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationRequest.Marshal(b, m, deterministic)
}
func (m *NotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationRequest.Merge(m, src)
}
func (m *NotificationRequest) XXX_Size() int {
	return xxx_messageInfo_NotificationRequest.Size(m)
}
func (m *NotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationRequest proto.InternalMessageInfo

func (m *NotificationRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type NotificationResponse struct {
	CreatedAt            string   `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Quota                int32    `protobuf:"varint,2,opt,name=quota,proto3" json:"quota,omitempty"`
	ThingDisplayName     string   `protobuf:"bytes,3,opt,name=thingDisplayName,proto3" json:"thingDisplayName,omitempty"`
	GatewayDisplayName   string   `protobuf:"bytes,4,opt,name=gatewayDisplayName,proto3" json:"gatewayDisplayName,omitempty"`
	ZoneDisplayName      string   `protobuf:"bytes,5,opt,name=zoneDisplayName,proto3" json:"zoneDisplayName,omitempty"`
	SecurityType         int32    `protobuf:"varint,6,opt,name=securityType,proto3" json:"securityType,omitempty"`
	Mode                 int32    `protobuf:"varint,7,opt,name=mode,proto3" json:"mode,omitempty"`
	Status               int32    `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	Template             string   `protobuf:"bytes,9,opt,name=template,proto3" json:"template,omitempty"`
	GatewayMacAddress    string   `protobuf:"bytes,10,opt,name=gatewayMacAddress,proto3" json:"gatewayMacAddress,omitempty"`
	CustomerNumber       string   `protobuf:"bytes,11,opt,name=customerNumber,proto3" json:"customerNumber,omitempty"`
	CanceledTime         string   `protobuf:"bytes,12,opt,name=canceledTime,proto3" json:"canceledTime,omitempty"`
	CallingTotal         int32    `protobuf:"varint,13,opt,name=calling_total,json=callingTotal,proto3" json:"calling_total,omitempty"`
	CallingComplete      int32    `protobuf:"varint,14,opt,name=calling_complete,json=callingComplete,proto3" json:"calling_complete,omitempty"`
	MessageTotal         int32    `protobuf:"varint,15,opt,name=message_total,json=messageTotal,proto3" json:"message_total,omitempty"`
	MessageComplete      int32    `protobuf:"varint,16,opt,name=message_complete,json=messageComplete,proto3" json:"message_complete,omitempty"`
	IsComplete           bool     `protobuf:"varint,17,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationResponse) Reset()         { *m = NotificationResponse{} }
func (m *NotificationResponse) String() string { return proto.CompactTextString(m) }
func (*NotificationResponse) ProtoMessage()    {}
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7388c87427bba644, []int{1}
}

func (m *NotificationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationResponse.Unmarshal(m, b)
}
func (m *NotificationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationResponse.Marshal(b, m, deterministic)
}
func (m *NotificationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationResponse.Merge(m, src)
}
func (m *NotificationResponse) XXX_Size() int {
	return xxx_messageInfo_NotificationResponse.Size(m)
}
func (m *NotificationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationResponse proto.InternalMessageInfo

func (m *NotificationResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *NotificationResponse) GetQuota() int32 {
	if m != nil {
		return m.Quota
	}
	return 0
}

func (m *NotificationResponse) GetThingDisplayName() string {
	if m != nil {
		return m.ThingDisplayName
	}
	return ""
}

func (m *NotificationResponse) GetGatewayDisplayName() string {
	if m != nil {
		return m.GatewayDisplayName
	}
	return ""
}

func (m *NotificationResponse) GetZoneDisplayName() string {
	if m != nil {
		return m.ZoneDisplayName
	}
	return ""
}

func (m *NotificationResponse) GetSecurityType() int32 {
	if m != nil {
		return m.SecurityType
	}
	return 0
}

func (m *NotificationResponse) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *NotificationResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *NotificationResponse) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

func (m *NotificationResponse) GetGatewayMacAddress() string {
	if m != nil {
		return m.GatewayMacAddress
	}
	return ""
}

func (m *NotificationResponse) GetCustomerNumber() string {
	if m != nil {
		return m.CustomerNumber
	}
	return ""
}

func (m *NotificationResponse) GetCanceledTime() string {
	if m != nil {
		return m.CanceledTime
	}
	return ""
}

func (m *NotificationResponse) GetCallingTotal() int32 {
	if m != nil {
		return m.CallingTotal
	}
	return 0
}

func (m *NotificationResponse) GetCallingComplete() int32 {
	if m != nil {
		return m.CallingComplete
	}
	return 0
}

func (m *NotificationResponse) GetMessageTotal() int32 {
	if m != nil {
		return m.MessageTotal
	}
	return 0
}

func (m *NotificationResponse) GetMessageComplete() int32 {
	if m != nil {
		return m.MessageComplete
	}
	return 0
}

func (m *NotificationResponse) GetIsComplete() bool {
	if m != nil {
		return m.IsComplete
	}
	return false
}

type CallingRequest struct {
	Thing                *Thing        `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	Gateway              *Thing        `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Template             *Thing        `protobuf:"bytes,3,opt,name=template,proto3" json:"template,omitempty"`
	Zone                 *Thing        `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`
	ClientConfig         *ClientConfig `protobuf:"bytes,5,opt,name=clientConfig,proto3" json:"clientConfig,omitempty"`
	CustomerNumber       string        `protobuf:"bytes,6,opt,name=customerNumber,proto3" json:"customerNumber,omitempty"`
	MacAddress           string        `protobuf:"bytes,7,opt,name=macAddress,proto3" json:"macAddress,omitempty"`
	ForceType            int32         `protobuf:"varint,8,opt,name=forceType,proto3" json:"forceType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CallingRequest) Reset()         { *m = CallingRequest{} }
func (m *CallingRequest) String() string { return proto.CompactTextString(m) }
func (*CallingRequest) ProtoMessage()    {}
func (*CallingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7388c87427bba644, []int{2}
}

func (m *CallingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallingRequest.Unmarshal(m, b)
}
func (m *CallingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallingRequest.Marshal(b, m, deterministic)
}
func (m *CallingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallingRequest.Merge(m, src)
}
func (m *CallingRequest) XXX_Size() int {
	return xxx_messageInfo_CallingRequest.Size(m)
}
func (m *CallingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CallingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CallingRequest proto.InternalMessageInfo

func (m *CallingRequest) GetThing() *Thing {
	if m != nil {
		return m.Thing
	}
	return nil
}

func (m *CallingRequest) GetGateway() *Thing {
	if m != nil {
		return m.Gateway
	}
	return nil
}

func (m *CallingRequest) GetTemplate() *Thing {
	if m != nil {
		return m.Template
	}
	return nil
}

func (m *CallingRequest) GetZone() *Thing {
	if m != nil {
		return m.Zone
	}
	return nil
}

func (m *CallingRequest) GetClientConfig() *ClientConfig {
	if m != nil {
		return m.ClientConfig
	}
	return nil
}

func (m *CallingRequest) GetCustomerNumber() string {
	if m != nil {
		return m.CustomerNumber
	}
	return ""
}

func (m *CallingRequest) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *CallingRequest) GetForceType() int32 {
	if m != nil {
		return m.ForceType
	}
	return 0
}

type Thing struct {
	DisplayName          string          `protobuf:"bytes,1,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Serial               string          `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
	Properties           []*Property     `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty"`
	Template             *SimpleTemplate `protobuf:"bytes,5,opt,name=template,proto3" json:"template,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Thing) Reset()         { *m = Thing{} }
func (m *Thing) String() string { return proto.CompactTextString(m) }
func (*Thing) ProtoMessage()    {}
func (*Thing) Descriptor() ([]byte, []int) {
	return fileDescriptor_7388c87427bba644, []int{3}
}

func (m *Thing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Thing.Unmarshal(m, b)
}
func (m *Thing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Thing.Marshal(b, m, deterministic)
}
func (m *Thing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Thing.Merge(m, src)
}
func (m *Thing) XXX_Size() int {
	return xxx_messageInfo_Thing.Size(m)
}
func (m *Thing) XXX_DiscardUnknown() {
	xxx_messageInfo_Thing.DiscardUnknown(m)
}

var xxx_messageInfo_Thing proto.InternalMessageInfo

func (m *Thing) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Thing) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Thing) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *Thing) GetProperties() []*Property {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Thing) GetTemplate() *SimpleTemplate {
	if m != nil {
		return m.Template
	}
	return nil
}

type SimpleTemplate struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleTemplate) Reset()         { *m = SimpleTemplate{} }
func (m *SimpleTemplate) String() string { return proto.CompactTextString(m) }
func (*SimpleTemplate) ProtoMessage()    {}
func (*SimpleTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_7388c87427bba644, []int{4}
}

func (m *SimpleTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleTemplate.Unmarshal(m, b)
}
func (m *SimpleTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleTemplate.Marshal(b, m, deterministic)
}
func (m *SimpleTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleTemplate.Merge(m, src)
}
func (m *SimpleTemplate) XXX_Size() int {
	return xxx_messageInfo_SimpleTemplate.Size(m)
}
func (m *SimpleTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleTemplate proto.InternalMessageInfo

func (m *SimpleTemplate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Property struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Property) Reset()         { *m = Property{} }
func (m *Property) String() string { return proto.CompactTextString(m) }
func (*Property) ProtoMessage()    {}
func (*Property) Descriptor() ([]byte, []int) {
	return fileDescriptor_7388c87427bba644, []int{5}
}

func (m *Property) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Property.Unmarshal(m, b)
}
func (m *Property) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Property.Marshal(b, m, deterministic)
}
func (m *Property) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Property.Merge(m, src)
}
func (m *Property) XXX_Size() int {
	return xxx_messageInfo_Property.Size(m)
}
func (m *Property) XXX_DiscardUnknown() {
	xxx_messageInfo_Property.DiscardUnknown(m)
}

var xxx_messageInfo_Property proto.InternalMessageInfo

func (m *Property) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Property) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// client config
type ClientConfig struct {
	Alias                string   `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	CustomerNumber       string   `protobuf:"bytes,2,opt,name=customerNumber,proto3" json:"customerNumber,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Setting              *Setting `protobuf:"bytes,4,opt,name=setting,proto3" json:"setting,omitempty"`
	Address1             string   `protobuf:"bytes,5,opt,name=address1,proto3" json:"address1,omitempty"`
	Address2             string   `protobuf:"bytes,6,opt,name=address2,proto3" json:"address2,omitempty"`
	FirstName            string   `protobuf:"bytes,7,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,8,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Mobile               string   `protobuf:"bytes,9,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientConfig) Reset()         { *m = ClientConfig{} }
func (m *ClientConfig) String() string { return proto.CompactTextString(m) }
func (*ClientConfig) ProtoMessage()    {}
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_7388c87427bba644, []int{6}
}

func (m *ClientConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientConfig.Unmarshal(m, b)
}
func (m *ClientConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientConfig.Marshal(b, m, deterministic)
}
func (m *ClientConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientConfig.Merge(m, src)
}
func (m *ClientConfig) XXX_Size() int {
	return xxx_messageInfo_ClientConfig.Size(m)
}
func (m *ClientConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ClientConfig proto.InternalMessageInfo

func (m *ClientConfig) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *ClientConfig) GetCustomerNumber() string {
	if m != nil {
		return m.CustomerNumber
	}
	return ""
}

func (m *ClientConfig) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ClientConfig) GetSetting() *Setting {
	if m != nil {
		return m.Setting
	}
	return nil
}

func (m *ClientConfig) GetAddress1() string {
	if m != nil {
		return m.Address1
	}
	return ""
}

func (m *ClientConfig) GetAddress2() string {
	if m != nil {
		return m.Address2
	}
	return ""
}

func (m *ClientConfig) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *ClientConfig) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *ClientConfig) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type Setting struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsAllowRegister      bool     `protobuf:"varint,2,opt,name=isAllowRegister,proto3" json:"isAllowRegister,omitempty"`
	Other                string   `protobuf:"bytes,3,opt,name=other,proto3" json:"other,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Setting) Reset()         { *m = Setting{} }
func (m *Setting) String() string { return proto.CompactTextString(m) }
func (*Setting) ProtoMessage()    {}
func (*Setting) Descriptor() ([]byte, []int) {
	return fileDescriptor_7388c87427bba644, []int{7}
}

func (m *Setting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Setting.Unmarshal(m, b)
}
func (m *Setting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Setting.Marshal(b, m, deterministic)
}
func (m *Setting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Setting.Merge(m, src)
}
func (m *Setting) XXX_Size() int {
	return xxx_messageInfo_Setting.Size(m)
}
func (m *Setting) XXX_DiscardUnknown() {
	xxx_messageInfo_Setting.DiscardUnknown(m)
}

var xxx_messageInfo_Setting proto.InternalMessageInfo

func (m *Setting) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Setting) GetIsAllowRegister() bool {
	if m != nil {
		return m.IsAllowRegister
	}
	return false
}

func (m *Setting) GetOther() string {
	if m != nil {
		return m.Other
	}
	return ""
}

type PhoneNumber struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Locale               string   `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	IsMaster             bool     `protobuf:"varint,3,opt,name=isMaster,proto3" json:"isMaster,omitempty"`
	IsSmsEnabled         bool     `protobuf:"varint,4,opt,name=isSmsEnabled,proto3" json:"isSmsEnabled,omitempty"`
	IsCallEnabled        bool     `protobuf:"varint,5,opt,name=isCallEnabled,proto3" json:"isCallEnabled,omitempty"`
	Timezone             string   `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneNumber) Reset()         { *m = PhoneNumber{} }
func (m *PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*PhoneNumber) ProtoMessage()    {}
func (*PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_7388c87427bba644, []int{8}
}

func (m *PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneNumber.Unmarshal(m, b)
}
func (m *PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneNumber.Merge(m, src)
}
func (m *PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_PhoneNumber.Size(m)
}
func (m *PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneNumber proto.InternalMessageInfo

func (m *PhoneNumber) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *PhoneNumber) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

func (m *PhoneNumber) GetIsMaster() bool {
	if m != nil {
		return m.IsMaster
	}
	return false
}

func (m *PhoneNumber) GetIsSmsEnabled() bool {
	if m != nil {
		return m.IsSmsEnabled
	}
	return false
}

func (m *PhoneNumber) GetIsCallEnabled() bool {
	if m != nil {
		return m.IsCallEnabled
	}
	return false
}

func (m *PhoneNumber) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

// response
type CallingResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallingResponse) Reset()         { *m = CallingResponse{} }
func (m *CallingResponse) String() string { return proto.CompactTextString(m) }
func (*CallingResponse) ProtoMessage()    {}
func (*CallingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7388c87427bba644, []int{9}
}

func (m *CallingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallingResponse.Unmarshal(m, b)
}
func (m *CallingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallingResponse.Marshal(b, m, deterministic)
}
func (m *CallingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallingResponse.Merge(m, src)
}
func (m *CallingResponse) XXX_Size() int {
	return xxx_messageInfo_CallingResponse.Size(m)
}
func (m *CallingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CallingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CallingResponse proto.InternalMessageInfo

func (m *CallingResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *CallingResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *CallingResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ModeRequest struct {
	Mode                 string   `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	GatewayMacAddress    string   `protobuf:"bytes,2,opt,name=gatewayMacAddress,proto3" json:"gatewayMacAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModeRequest) Reset()         { *m = ModeRequest{} }
func (m *ModeRequest) String() string { return proto.CompactTextString(m) }
func (*ModeRequest) ProtoMessage()    {}
func (*ModeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7388c87427bba644, []int{10}
}

func (m *ModeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModeRequest.Unmarshal(m, b)
}
func (m *ModeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModeRequest.Marshal(b, m, deterministic)
}
func (m *ModeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModeRequest.Merge(m, src)
}
func (m *ModeRequest) XXX_Size() int {
	return xxx_messageInfo_ModeRequest.Size(m)
}
func (m *ModeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModeRequest proto.InternalMessageInfo

func (m *ModeRequest) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *ModeRequest) GetGatewayMacAddress() string {
	if m != nil {
		return m.GatewayMacAddress
	}
	return ""
}

type Response struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Sid                  string   `protobuf:"bytes,3,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_7388c87427bba644, []int{11}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type QuotaRequest struct {
	CustomerNumber       string   `protobuf:"bytes,1,opt,name=customerNumber,proto3" json:"customerNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuotaRequest) Reset()         { *m = QuotaRequest{} }
func (m *QuotaRequest) String() string { return proto.CompactTextString(m) }
func (*QuotaRequest) ProtoMessage()    {}
func (*QuotaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7388c87427bba644, []int{12}
}

func (m *QuotaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuotaRequest.Unmarshal(m, b)
}
func (m *QuotaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuotaRequest.Marshal(b, m, deterministic)
}
func (m *QuotaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuotaRequest.Merge(m, src)
}
func (m *QuotaRequest) XXX_Size() int {
	return xxx_messageInfo_QuotaRequest.Size(m)
}
func (m *QuotaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuotaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuotaRequest proto.InternalMessageInfo

func (m *QuotaRequest) GetCustomerNumber() string {
	if m != nil {
		return m.CustomerNumber
	}
	return ""
}

type QuotaResponse struct {
	Quota                int32    `protobuf:"varint,1,opt,name=quota,proto3" json:"quota,omitempty"`
	CustomerNumber       string   `protobuf:"bytes,2,opt,name=customerNumber,proto3" json:"customerNumber,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuotaResponse) Reset()         { *m = QuotaResponse{} }
func (m *QuotaResponse) String() string { return proto.CompactTextString(m) }
func (*QuotaResponse) ProtoMessage()    {}
func (*QuotaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7388c87427bba644, []int{13}
}

func (m *QuotaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuotaResponse.Unmarshal(m, b)
}
func (m *QuotaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuotaResponse.Marshal(b, m, deterministic)
}
func (m *QuotaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuotaResponse.Merge(m, src)
}
func (m *QuotaResponse) XXX_Size() int {
	return xxx_messageInfo_QuotaResponse.Size(m)
}
func (m *QuotaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuotaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuotaResponse proto.InternalMessageInfo

func (m *QuotaResponse) GetQuota() int32 {
	if m != nil {
		return m.Quota
	}
	return 0
}

func (m *QuotaResponse) GetCustomerNumber() string {
	if m != nil {
		return m.CustomerNumber
	}
	return ""
}

func (m *QuotaResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type VoiceRequest struct {
	SecurityType         string   `protobuf:"bytes,1,opt,name=securityType,proto3" json:"securityType,omitempty"`
	FileName             string   `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoiceRequest) Reset()         { *m = VoiceRequest{} }
func (m *VoiceRequest) String() string { return proto.CompactTextString(m) }
func (*VoiceRequest) ProtoMessage()    {}
func (*VoiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7388c87427bba644, []int{14}
}

func (m *VoiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoiceRequest.Unmarshal(m, b)
}
func (m *VoiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoiceRequest.Marshal(b, m, deterministic)
}
func (m *VoiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoiceRequest.Merge(m, src)
}
func (m *VoiceRequest) XXX_Size() int {
	return xxx_messageInfo_VoiceRequest.Size(m)
}
func (m *VoiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VoiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VoiceRequest proto.InternalMessageInfo

func (m *VoiceRequest) GetSecurityType() string {
	if m != nil {
		return m.SecurityType
	}
	return ""
}

func (m *VoiceRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type VoiceResponse struct {
	Xml                  string   `protobuf:"bytes,1,opt,name=xml,proto3" json:"xml,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoiceResponse) Reset()         { *m = VoiceResponse{} }
func (m *VoiceResponse) String() string { return proto.CompactTextString(m) }
func (*VoiceResponse) ProtoMessage()    {}
func (*VoiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7388c87427bba644, []int{15}
}

func (m *VoiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoiceResponse.Unmarshal(m, b)
}
func (m *VoiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoiceResponse.Marshal(b, m, deterministic)
}
func (m *VoiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoiceResponse.Merge(m, src)
}
func (m *VoiceResponse) XXX_Size() int {
	return xxx_messageInfo_VoiceResponse.Size(m)
}
func (m *VoiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VoiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VoiceResponse proto.InternalMessageInfo

func (m *VoiceResponse) GetXml() string {
	if m != nil {
		return m.Xml
	}
	return ""
}

type UpdateCallRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=Sid,proto3" json:"Sid,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=From,proto3" json:"From,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=To,proto3" json:"To,omitempty"`
	CallStatus           string   `protobuf:"bytes,4,opt,name=CallStatus,proto3" json:"CallStatus,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,5,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
	DateCreated          string   `protobuf:"bytes,6,opt,name=DateCreated,proto3" json:"DateCreated,omitempty"`
	DateUpdated          string   `protobuf:"bytes,7,opt,name=DateUpdated,proto3" json:"DateUpdated,omitempty"`
	StartTime            string   `protobuf:"bytes,8,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime              string   `protobuf:"bytes,9,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	Duration             string   `protobuf:"bytes,10,opt,name=Duration,proto3" json:"Duration,omitempty"`
	ForwardedFrom        string   `protobuf:"bytes,11,opt,name=ForwardedFrom,proto3" json:"ForwardedFrom,omitempty"`
	Price                string   `protobuf:"bytes,12,opt,name=Price,proto3" json:"Price,omitempty"`
	PriceUnit            string   `protobuf:"bytes,13,opt,name=PriceUnit,proto3" json:"PriceUnit,omitempty"`
	NotificationID       string   `protobuf:"bytes,14,opt,name=NotificationID,proto3" json:"NotificationID,omitempty"`
	CallID               string   `protobuf:"bytes,15,opt,name=CallID,proto3" json:"CallID,omitempty"`
	CallerCountry        string   `protobuf:"bytes,16,opt,name=CallerCountry,proto3" json:"CallerCountry,omitempty"`
	ToCountry            string   `protobuf:"bytes,17,opt,name=ToCountry,proto3" json:"ToCountry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCallRequest) Reset()         { *m = UpdateCallRequest{} }
func (m *UpdateCallRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCallRequest) ProtoMessage()    {}
func (*UpdateCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7388c87427bba644, []int{16}
}

func (m *UpdateCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCallRequest.Unmarshal(m, b)
}
func (m *UpdateCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCallRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCallRequest.Merge(m, src)
}
func (m *UpdateCallRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCallRequest.Size(m)
}
func (m *UpdateCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCallRequest proto.InternalMessageInfo

func (m *UpdateCallRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *UpdateCallRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *UpdateCallRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *UpdateCallRequest) GetCallStatus() string {
	if m != nil {
		return m.CallStatus
	}
	return ""
}

func (m *UpdateCallRequest) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *UpdateCallRequest) GetDateCreated() string {
	if m != nil {
		return m.DateCreated
	}
	return ""
}

func (m *UpdateCallRequest) GetDateUpdated() string {
	if m != nil {
		return m.DateUpdated
	}
	return ""
}

func (m *UpdateCallRequest) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *UpdateCallRequest) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *UpdateCallRequest) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func (m *UpdateCallRequest) GetForwardedFrom() string {
	if m != nil {
		return m.ForwardedFrom
	}
	return ""
}

func (m *UpdateCallRequest) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *UpdateCallRequest) GetPriceUnit() string {
	if m != nil {
		return m.PriceUnit
	}
	return ""
}

func (m *UpdateCallRequest) GetNotificationID() string {
	if m != nil {
		return m.NotificationID
	}
	return ""
}

func (m *UpdateCallRequest) GetCallID() string {
	if m != nil {
		return m.CallID
	}
	return ""
}

func (m *UpdateCallRequest) GetCallerCountry() string {
	if m != nil {
		return m.CallerCountry
	}
	return ""
}

func (m *UpdateCallRequest) GetToCountry() string {
	if m != nil {
		return m.ToCountry
	}
	return ""
}

type UpdateMessageRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=Sid,proto3" json:"Sid,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=From,proto3" json:"From,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=To,proto3" json:"To,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,5,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
	DateSent             string   `protobuf:"bytes,6,opt,name=DateSent,proto3" json:"DateSent,omitempty"`
	DateUpdated          string   `protobuf:"bytes,7,opt,name=DateUpdated,proto3" json:"DateUpdated,omitempty"`
	Segments             string   `protobuf:"bytes,8,opt,name=Segments,proto3" json:"Segments,omitempty"`
	Price                string   `protobuf:"bytes,9,opt,name=Price,proto3" json:"Price,omitempty"`
	PriceUnit            string   `protobuf:"bytes,10,opt,name=PriceUnit,proto3" json:"PriceUnit,omitempty"`
	NotificationID       string   `protobuf:"bytes,11,opt,name=NotificationID,proto3" json:"NotificationID,omitempty"`
	MessageID            string   `protobuf:"bytes,12,opt,name=MessageID,proto3" json:"MessageID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMessageRequest) Reset()         { *m = UpdateMessageRequest{} }
func (m *UpdateMessageRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMessageRequest) ProtoMessage()    {}
func (*UpdateMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7388c87427bba644, []int{17}
}

func (m *UpdateMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMessageRequest.Unmarshal(m, b)
}
func (m *UpdateMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMessageRequest.Marshal(b, m, deterministic)
}
func (m *UpdateMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMessageRequest.Merge(m, src)
}
func (m *UpdateMessageRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMessageRequest.Size(m)
}
func (m *UpdateMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMessageRequest proto.InternalMessageInfo

func (m *UpdateMessageRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *UpdateMessageRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *UpdateMessageRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *UpdateMessageRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UpdateMessageRequest) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *UpdateMessageRequest) GetDateSent() string {
	if m != nil {
		return m.DateSent
	}
	return ""
}

func (m *UpdateMessageRequest) GetDateUpdated() string {
	if m != nil {
		return m.DateUpdated
	}
	return ""
}

func (m *UpdateMessageRequest) GetSegments() string {
	if m != nil {
		return m.Segments
	}
	return ""
}

func (m *UpdateMessageRequest) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *UpdateMessageRequest) GetPriceUnit() string {
	if m != nil {
		return m.PriceUnit
	}
	return ""
}

func (m *UpdateMessageRequest) GetNotificationID() string {
	if m != nil {
		return m.NotificationID
	}
	return ""
}

func (m *UpdateMessageRequest) GetMessageID() string {
	if m != nil {
		return m.MessageID
	}
	return ""
}

func init() {
	proto.RegisterType((*NotificationRequest)(nil), "calling.NotificationRequest")
	proto.RegisterType((*NotificationResponse)(nil), "calling.NotificationResponse")
	proto.RegisterType((*CallingRequest)(nil), "calling.CallingRequest")
	proto.RegisterType((*Thing)(nil), "calling.Thing")
	proto.RegisterType((*SimpleTemplate)(nil), "calling.SimpleTemplate")
	proto.RegisterType((*Property)(nil), "calling.Property")
	proto.RegisterType((*ClientConfig)(nil), "calling.ClientConfig")
	proto.RegisterType((*Setting)(nil), "calling.Setting")
	proto.RegisterType((*PhoneNumber)(nil), "calling.PhoneNumber")
	proto.RegisterType((*CallingResponse)(nil), "calling.CallingResponse")
	proto.RegisterType((*ModeRequest)(nil), "calling.ModeRequest")
	proto.RegisterType((*Response)(nil), "calling.Response")
	proto.RegisterType((*QuotaRequest)(nil), "calling.QuotaRequest")
	proto.RegisterType((*QuotaResponse)(nil), "calling.QuotaResponse")
	proto.RegisterType((*VoiceRequest)(nil), "calling.VoiceRequest")
	proto.RegisterType((*VoiceResponse)(nil), "calling.VoiceResponse")
	proto.RegisterType((*UpdateCallRequest)(nil), "calling.UpdateCallRequest")
	proto.RegisterType((*UpdateMessageRequest)(nil), "calling.UpdateMessageRequest")
}

func init() { proto.RegisterFile("calling.proto", fileDescriptor_7388c87427bba644) }

var fileDescriptor_7388c87427bba644 = []byte{
	// 1353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x57, 0x6d, 0x6f, 0xdc, 0xc4,
	0x13, 0xff, 0xe7, 0x92, 0xcb, 0x5d, 0xe6, 0xf2, 0xb8, 0xff, 0x50, 0xac, 0xa8, 0x85, 0x62, 0x2a,
	0xd4, 0x22, 0x54, 0xa9, 0x29, 0x42, 0x20, 0xc4, 0x8b, 0x92, 0xb4, 0x08, 0xa4, 0x84, 0xe0, 0xbb,
	0x22, 0xf1, 0xaa, 0x72, 0xec, 0x4d, 0xba, 0x92, 0xed, 0xbd, 0xda, 0xeb, 0x96, 0xe3, 0x2d, 0x5f,
	0x82, 0x2f, 0xc0, 0xc7, 0xe0, 0x43, 0xf0, 0x9e, 0x0f, 0xc2, 0x4b, 0x66, 0xf6, 0xc9, 0xf6, 0x9d,
	0xab, 0x52, 0xf1, 0x6e, 0xe7, 0x37, 0xb3, 0xe3, 0xd9, 0x99, 0xdf, 0xce, 0x8e, 0x61, 0x27, 0x89,
	0xb3, 0x4c, 0x14, 0xd7, 0xf7, 0xe7, 0xa5, 0x54, 0x92, 0x8d, 0xac, 0x18, 0xde, 0x83, 0xff, 0x9f,
	0x4b, 0x25, 0xae, 0x44, 0x12, 0x2b, 0x21, 0x8b, 0x88, 0xbf, 0xa8, 0x79, 0xa5, 0x18, 0x83, 0x8d,
	0xba, 0x16, 0x69, 0xb0, 0x76, 0x7b, 0xed, 0xee, 0x56, 0xa4, 0xd7, 0xe1, 0xdf, 0x1b, 0x70, 0xd8,
	0xb5, 0xad, 0xe6, 0xb2, 0xa8, 0x38, 0xbb, 0x05, 0x90, 0x94, 0x3c, 0x56, 0x3c, 0x7d, 0x16, 0x2b,
	0xbb, 0x65, 0xcb, 0x22, 0x8f, 0x14, 0x3b, 0x84, 0xe1, 0x8b, 0x5a, 0xaa, 0x38, 0x18, 0xa0, 0x66,
	0x18, 0x19, 0x81, 0x7d, 0x0c, 0xfb, 0xea, 0x39, 0x46, 0x70, 0x2a, 0xaa, 0x79, 0x16, 0x2f, 0xce,
	0xe3, 0x9c, 0x07, 0xeb, 0x7a, 0xeb, 0x0a, 0xce, 0xee, 0x03, 0xbb, 0x46, 0x67, 0xaf, 0xe2, 0x45,
	0xdb, 0x7a, 0x43, 0x5b, 0xf7, 0x68, 0xd8, 0x5d, 0xd8, 0xfb, 0x45, 0x16, 0xbc, 0x6d, 0x3c, 0xd4,
	0xc6, 0xcb, 0x30, 0x0b, 0x61, 0xbb, 0xe2, 0x49, 0x5d, 0x0a, 0xb5, 0x98, 0x2d, 0xe6, 0x3c, 0xd8,
	0xd4, 0x21, 0x76, 0x30, 0xca, 0x45, 0x2e, 0x53, 0x1e, 0x8c, 0xb4, 0x4e, 0xaf, 0xd9, 0x0d, 0xd8,
	0xac, 0x54, 0xac, 0xea, 0x2a, 0x18, 0x6b, 0xd4, 0x4a, 0xec, 0x08, 0xc6, 0x8a, 0xe7, 0xe8, 0x5e,
	0xf1, 0x60, 0x4b, 0x7f, 0xd2, 0xcb, 0xec, 0x13, 0x38, 0xb0, 0xb1, 0x9e, 0xc5, 0xc9, 0xa3, 0x34,
	0x2d, 0x79, 0x55, 0x05, 0xa0, 0x8d, 0x56, 0x15, 0xec, 0x23, 0xd8, 0x4d, 0xea, 0x4a, 0xc9, 0x9c,
	0x97, 0xe7, 0x75, 0x7e, 0xc9, 0xcb, 0x60, 0xa2, 0x4d, 0x97, 0x50, 0x3a, 0x41, 0x12, 0x17, 0x09,
	0xcf, 0x78, 0x3a, 0x13, 0x78, 0xd0, 0x6d, 0x6d, 0xd5, 0xc1, 0xd8, 0x87, 0xbe, 0xfc, 0xcf, 0x14,
	0xe6, 0x3e, 0x0b, 0x76, 0xcc, 0x31, 0x2d, 0x38, 0x23, 0x8c, 0xdd, 0x83, 0x7d, 0x67, 0x94, 0x48,
	0x0c, 0x99, 0xe3, 0x11, 0x76, 0xb5, 0xdd, 0x9e, 0xc5, 0x4f, 0x2c, 0x4c, 0xfe, 0x72, 0x8c, 0x31,
	0xbe, 0xe6, 0xd6, 0xdf, 0x9e, 0xf1, 0x67, 0x41, 0xef, 0xcf, 0x19, 0x79, 0x7f, 0xfb, 0xc6, 0x9f,
	0xc5, 0xbd, 0xbf, 0xf7, 0x61, 0x22, 0xaa, 0xc6, 0xea, 0x00, 0xad, 0xc6, 0x11, 0x88, 0xca, 0x19,
	0x84, 0x7f, 0x0e, 0x60, 0xf7, 0xc4, 0x04, 0xe1, 0x18, 0x7a, 0x07, 0x86, 0x9a, 0x27, 0x9a, 0x6f,
	0x93, 0xe3, 0xdd, 0xfb, 0x8e, 0xe0, 0x33, 0x42, 0x23, 0xa3, 0x44, 0x26, 0x8c, 0x6c, 0x6a, 0x35,
	0xfb, 0x56, 0xed, 0x9c, 0x1a, 0xf9, 0xd8, 0x54, 0x6e, 0xbd, 0xd7, 0xb4, 0xa9, 0x64, 0x08, 0x1b,
	0x44, 0x24, 0xcd, 0xc0, 0x55, 0x3b, 0xad, 0x63, 0x5f, 0x60, 0x5d, 0x32, 0xc1, 0x0b, 0x75, 0x22,
	0x8b, 0x2b, 0x71, 0xad, 0x09, 0x38, 0x39, 0x7e, 0xc7, 0xdb, 0x9e, 0xb4, 0x94, 0x51, 0xc7, 0xb4,
	0xa7, 0xf4, 0x9b, 0xbd, 0xa5, 0x7f, 0x0f, 0x20, 0x6f, 0x98, 0x34, 0xd2, 0x36, 0x2d, 0x84, 0xdd,
	0x84, 0xad, 0x2b, 0x59, 0x26, 0x5c, 0x33, 0xdb, 0xf0, 0xb4, 0x01, 0xc2, 0x3f, 0xd6, 0x60, 0xa8,
	0x03, 0x66, 0xb7, 0x61, 0x92, 0xb6, 0xae, 0x8a, 0xb9, 0xc0, 0x6d, 0x88, 0xae, 0x40, 0x41, 0xaa,
	0x81, 0x69, 0x07, 0xb4, 0xd6, 0x57, 0x80, 0x97, 0x02, 0xab, 0x6f, 0xae, 0xad, 0x95, 0xd8, 0x03,
	0x00, 0xec, 0x31, 0x73, 0x5e, 0x2a, 0xc1, 0x2b, 0x4c, 0xd1, 0x3a, 0x1e, 0xfb, 0xc0, 0x1f, 0xfb,
	0xc2, 0xa8, 0x16, 0x51, 0xcb, 0x88, 0x3d, 0x6c, 0xe5, 0xde, 0xe4, 0xe9, 0x5d, 0xbf, 0x61, 0x2a,
	0x88, 0x03, 0x33, 0xab, 0x6e, 0x8a, 0x10, 0xde, 0x81, 0xdd, 0xae, 0xce, 0x47, 0xb9, 0xd6, 0x44,
	0x19, 0x7e, 0x0a, 0x63, 0xf7, 0xc9, 0x3e, 0x3d, 0x35, 0xa7, 0x97, 0x71, 0x56, 0xbb, 0xa3, 0x19,
	0x21, 0xfc, 0x6d, 0x00, 0xdb, 0xed, 0x02, 0x91, 0x59, 0x9c, 0x89, 0xb8, 0xb2, 0x7b, 0x8d, 0xd0,
	0x53, 0xa8, 0x41, 0x6f, 0xa1, 0x70, 0x37, 0xcf, 0x63, 0xe1, 0x32, 0x65, 0x04, 0x64, 0xdc, 0xa8,
	0xe2, 0x4a, 0x11, 0x87, 0x0d, 0x91, 0xf6, 0x9b, 0x43, 0x1b, 0x3c, 0x72, 0x06, 0xd4, 0x57, 0x62,
	0x53, 0xd5, 0x07, 0xb6, 0x95, 0x79, 0xb9, 0xa5, 0x3b, 0xb6, 0x44, 0xf1, 0xb2, 0xa6, 0x80, 0x28,
	0x2b, 0xa5, 0x0b, 0x6b, 0x18, 0xd2, 0x00, 0xb4, 0x33, 0x8b, 0xad, 0x72, 0x6c, 0x76, 0x3a, 0x99,
	0xca, 0x9b, 0xcb, 0x4b, 0x91, 0xb9, 0x3e, 0x66, 0xa5, 0xf0, 0x27, 0x18, 0xd9, 0xe8, 0xd8, 0x2e,
	0x0c, 0xec, 0x13, 0x31, 0x8c, 0x70, 0x45, 0x6d, 0x57, 0x54, 0x8f, 0xb2, 0x4c, 0xbe, 0x8a, 0xf8,
	0xb5, 0xa8, 0x94, 0xcd, 0xc7, 0x38, 0x5a, 0x86, 0x29, 0x21, 0x52, 0x3d, 0x47, 0xbd, 0x4d, 0x88,
	0x16, 0x88, 0x91, 0x93, 0x8b, 0xe7, 0x78, 0x79, 0x9a, 0xb4, 0xcd, 0x49, 0x74, 0x49, 0xd7, 0x02,
	0x05, 0x96, 0x49, 0x4c, 0x94, 0x2b, 0x99, 0x95, 0xe8, 0x30, 0xa2, 0x3a, 0x8b, 0xf5, 0x67, 0xd7,
	0xf5, 0x67, 0xbd, 0x4c, 0x4d, 0x52, 0x54, 0xd3, 0xbc, 0x7a, 0x5c, 0xc4, 0x97, 0xd8, 0x14, 0x75,
	0xbe, 0xc7, 0x51, 0x07, 0xc3, 0x86, 0xb2, 0x83, 0x1d, 0x07, 0x0b, 0xe0, 0x8c, 0x86, 0xda, 0xa8,
	0x0b, 0xea, 0x06, 0x8f, 0x2d, 0x55, 0x5f, 0x7f, 0x9b, 0x6c, 0x27, 0x87, 0x09, 0xec, 0xf9, 0x26,
	0x65, 0x9f, 0x46, 0x0c, 0x16, 0x0b, 0x51, 0x67, 0xe6, 0x59, 0x1c, 0x47, 0x56, 0xa2, 0x80, 0x78,
	0x59, 0xca, 0xf2, 0xcc, 0x74, 0x42, 0x7b, 0x94, 0x0e, 0xa6, 0x59, 0x43, 0xb2, 0x67, 0x0d, 0x09,
	0xe1, 0xf7, 0x30, 0x39, 0xc3, 0x17, 0xa8, 0xf5, 0x50, 0xeb, 0xc7, 0xc9, 0x72, 0x5a, 0x3f, 0x4e,
	0xbd, 0x0f, 0xcd, 0xe0, 0x35, 0x0f, 0x4d, 0xf8, 0x1d, 0x8c, 0xdf, 0x18, 0xae, 0x0f, 0x65, 0xd0,
	0x0a, 0x85, 0xed, 0xc3, 0x7a, 0x85, 0x04, 0x30, 0xe1, 0xd1, 0x32, 0xfc, 0x0c, 0xb6, 0x7f, 0xa0,
	0xd7, 0xdd, 0x45, 0xb7, 0x7a, 0x41, 0xd6, 0xfa, 0x2e, 0x08, 0x66, 0x6e, 0xc7, 0xee, 0xb3, 0x81,
	0xf8, 0x99, 0x61, 0xad, 0x3d, 0x33, 0xbc, 0xcd, 0x7d, 0x5b, 0xcd, 0xdc, 0x39, 0x6c, 0xff, 0x28,
	0x45, 0xe2, 0x53, 0xb7, 0xfc, 0xf6, 0x9b, 0xd0, 0xba, 0x6f, 0x3f, 0x96, 0xfb, 0x0a, 0x59, 0x7f,
	0xde, 0x34, 0x3f, 0x2f, 0x87, 0x1f, 0xc0, 0x8e, 0xf5, 0x67, 0x83, 0xc6, 0x7c, 0xfc, 0x9c, 0x67,
	0xd6, 0x0f, 0x2d, 0xc3, 0x5f, 0x37, 0xe0, 0xe0, 0xe9, 0x3c, 0xc5, 0x9c, 0x13, 0x31, 0xdc, 0x87,
	0xd1, 0x6e, 0xea, 0x67, 0x2b, 0x5a, 0x52, 0x15, 0x9f, 0x94, 0x32, 0x77, 0xfd, 0x95, 0xd6, 0x74,
	0xbb, 0x66, 0xd2, 0x9e, 0x00, 0x57, 0xd4, 0xed, 0xc9, 0xc9, 0xd4, 0x8c, 0x1d, 0x66, 0xf8, 0x69,
	0x21, 0x74, 0x9c, 0xc7, 0x6d, 0x4a, 0x99, 0x36, 0xd1, 0xc1, 0xa8, 0xd3, 0x9f, 0x52, 0x30, 0x66,
	0x36, 0xb3, 0x04, 0x6e, 0x43, 0xce, 0xc2, 0x04, 0x9d, 0xda, 0x96, 0xd1, 0x86, 0xa8, 0xa5, 0xe0,
	0x17, 0x4b, 0xa5, 0xa7, 0x0d, 0xd3, 0x35, 0x1a, 0x80, 0x05, 0x30, 0x7a, 0x5c, 0x98, 0x49, 0xc4,
	0xf4, 0x0d, 0x27, 0x52, 0x2a, 0x4f, 0xeb, 0x52, 0x4f, 0x8e, 0x76, 0xea, 0xf1, 0x32, 0xdd, 0xbd,
	0x27, 0xb2, 0x7c, 0x15, 0x97, 0x29, 0x4f, 0x75, 0x22, 0xcc, 0xac, 0xd3, 0x05, 0xa9, 0xac, 0x17,
	0x25, 0x26, 0xdc, 0xce, 0x38, 0x46, 0xa0, 0x78, 0xf4, 0xe2, 0x69, 0x21, 0x94, 0x1e, 0x6c, 0x30,
	0x1e, 0x0f, 0x10, 0x65, 0xda, 0x33, 0xeb, 0xb7, 0xa7, 0x7a, 0xa6, 0x41, 0xca, 0x74, 0x51, 0x62,
	0x3e, 0xe5, 0x12, 0xf5, 0x7b, 0xa6, 0xab, 0x18, 0x89, 0x22, 0xa3, 0x15, 0x2f, 0x4f, 0x64, 0x5d,
	0xa8, 0x72, 0xa1, 0x47, 0x18, 0x8c, 0xac, 0x03, 0x52, 0x0c, 0x33, 0xe9, 0x2c, 0x0e, 0x4c, 0x0c,
	0x1e, 0x08, 0xff, 0x1a, 0xc0, 0xa1, 0xc9, 0x9e, 0xad, 0xc3, 0x7f, 0x23, 0x02, 0x86, 0xda, 0x21,
	0xc1, 0xe6, 0x5b, 0x10, 0x80, 0x8a, 0x80, 0x71, 0x4c, 0xf1, 0x65, 0x73, 0xed, 0xcb, 0xc9, 0xff,
	0xa2, 0xf4, 0xb8, 0x7b, 0xca, 0xaf, 0x73, 0x34, 0xae, 0xdc, 0x7b, 0xe1, 0xe4, 0xa6, 0x38, 0x5b,
	0xaf, 0x2d, 0x0e, 0xbc, 0xb9, 0x38, 0x93, 0xde, 0xe2, 0xa0, 0x17, 0x7b, 0x00, 0x34, 0x31, 0xc5,
	0x6f, 0x80, 0xe3, 0xdf, 0xd7, 0x81, 0x4d, 0xed, 0xa5, 0xb5, 0xfd, 0x77, 0xfa, 0x32, 0x61, 0x5f,
	0xc3, 0x04, 0x8f, 0x95, 0xba, 0x5c, 0x37, 0x13, 0x45, 0x77, 0x90, 0x3c, 0x0a, 0x56, 0x15, 0xe6,
	0x3e, 0x87, 0xff, 0x63, 0x9f, 0xa3, 0x0f, 0x25, 0xe7, 0x56, 0xc1, 0x0e, 0xbd, 0x69, 0xab, 0x05,
	0x1f, 0x35, 0xc3, 0x4d, 0x6b, 0xe7, 0x97, 0x30, 0xfe, 0x86, 0x2b, 0xdd, 0xd4, 0x58, 0x33, 0xf4,
	0xb5, 0x9b, 0xe3, 0xd1, 0x8d, 0x65, 0xd8, 0x6f, 0xfe, 0x0a, 0xa0, 0xe9, 0x1a, 0xec, 0xc8, 0xdb,
	0xad, 0xb4, 0x92, 0xfe, 0x6f, 0x9f, 0xc0, 0x4e, 0x87, 0x6e, 0xec, 0xd6, 0x92, 0x87, 0x2e, 0x0d,
	0xfb, 0x9d, 0x5c, 0xc0, 0x1e, 0x1e, 0xa0, 0x5d, 0x08, 0x76, 0xd3, 0xdb, 0xf5, 0xfc, 0x32, 0x1e,
	0xdd, 0x7a, 0x8d, 0xd6, 0x79, 0xbc, 0xdc, 0xd4, 0xbf, 0x9e, 0x0f, 0xff, 0x09, 0x00, 0x00, 0xff,
	0xff, 0xb1, 0x82, 0x38, 0x94, 0x8b, 0x0e, 0x00, 0x00,
}
