// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simple-notification/message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Thing          *Thing `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	Gateway        *Thing `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Template       *Thing `protobuf:"bytes,3,opt,name=template,proto3" json:"template,omitempty"`
	Zone           *Thing `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`
	CustomerNumber string `protobuf:"bytes,5,opt,name=customerNumber,proto3" json:"customerNumber,omitempty"`
	MacAddress     string `protobuf:"bytes,8,opt,name=macAddress,proto3" json:"macAddress,omitempty"`
	// notification type are below
	// DoorSensor
	// MotionSensor
	// SecurityBreach
	// SafetyBreachCO
	// SafetyBreachSOS
	// SafetyBreachSmoke
	// SecurityAlarm
	// SafetyAlarm
	Type                 int32    `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_94158a4fda103638, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetThing() *Thing {
	if m != nil {
		return m.Thing
	}
	return nil
}

func (m *Request) GetGateway() *Thing {
	if m != nil {
		return m.Gateway
	}
	return nil
}

func (m *Request) GetTemplate() *Thing {
	if m != nil {
		return m.Template
	}
	return nil
}

func (m *Request) GetZone() *Thing {
	if m != nil {
		return m.Zone
	}
	return nil
}

func (m *Request) GetCustomerNumber() string {
	if m != nil {
		return m.CustomerNumber
	}
	return ""
}

func (m *Request) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *Request) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Request) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Response struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_94158a4fda103638, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *Response) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type Thing struct {
	DisplayName          string          `protobuf:"bytes,1,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Serial               string          `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
	Properties           []*Property     `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty"`
	Template             *SimpleTemplate `protobuf:"bytes,5,opt,name=template,proto3" json:"template,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Thing) Reset()         { *m = Thing{} }
func (m *Thing) String() string { return proto.CompactTextString(m) }
func (*Thing) ProtoMessage()    {}
func (*Thing) Descriptor() ([]byte, []int) {
	return fileDescriptor_94158a4fda103638, []int{2}
}

func (m *Thing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Thing.Unmarshal(m, b)
}
func (m *Thing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Thing.Marshal(b, m, deterministic)
}
func (m *Thing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Thing.Merge(m, src)
}
func (m *Thing) XXX_Size() int {
	return xxx_messageInfo_Thing.Size(m)
}
func (m *Thing) XXX_DiscardUnknown() {
	xxx_messageInfo_Thing.DiscardUnknown(m)
}

var xxx_messageInfo_Thing proto.InternalMessageInfo

func (m *Thing) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Thing) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Thing) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *Thing) GetProperties() []*Property {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Thing) GetTemplate() *SimpleTemplate {
	if m != nil {
		return m.Template
	}
	return nil
}

type SimpleTemplate struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleTemplate) Reset()         { *m = SimpleTemplate{} }
func (m *SimpleTemplate) String() string { return proto.CompactTextString(m) }
func (*SimpleTemplate) ProtoMessage()    {}
func (*SimpleTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_94158a4fda103638, []int{3}
}

func (m *SimpleTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleTemplate.Unmarshal(m, b)
}
func (m *SimpleTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleTemplate.Marshal(b, m, deterministic)
}
func (m *SimpleTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleTemplate.Merge(m, src)
}
func (m *SimpleTemplate) XXX_Size() int {
	return xxx_messageInfo_SimpleTemplate.Size(m)
}
func (m *SimpleTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleTemplate proto.InternalMessageInfo

func (m *SimpleTemplate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Property struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Property) Reset()         { *m = Property{} }
func (m *Property) String() string { return proto.CompactTextString(m) }
func (*Property) ProtoMessage()    {}
func (*Property) Descriptor() ([]byte, []int) {
	return fileDescriptor_94158a4fda103638, []int{4}
}

func (m *Property) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Property.Unmarshal(m, b)
}
func (m *Property) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Property.Marshal(b, m, deterministic)
}
func (m *Property) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Property.Merge(m, src)
}
func (m *Property) XXX_Size() int {
	return xxx_messageInfo_Property.Size(m)
}
func (m *Property) XXX_DiscardUnknown() {
	xxx_messageInfo_Property.DiscardUnknown(m)
}

var xxx_messageInfo_Property proto.InternalMessageInfo

func (m *Property) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Property) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetNotificationRequest struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Serial               string   `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNotificationRequest) Reset()         { *m = GetNotificationRequest{} }
func (m *GetNotificationRequest) String() string { return proto.CompactTextString(m) }
func (*GetNotificationRequest) ProtoMessage()    {}
func (*GetNotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_94158a4fda103638, []int{5}
}

func (m *GetNotificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNotificationRequest.Unmarshal(m, b)
}
func (m *GetNotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNotificationRequest.Marshal(b, m, deterministic)
}
func (m *GetNotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNotificationRequest.Merge(m, src)
}
func (m *GetNotificationRequest) XXX_Size() int {
	return xxx_messageInfo_GetNotificationRequest.Size(m)
}
func (m *GetNotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNotificationRequest proto.InternalMessageInfo

func (m *GetNotificationRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetNotificationRequest) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

type GetNotificationResponse struct {
	Success              bool                  `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage         string                `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	Data                 []*NotificationResult `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetNotificationResponse) Reset()         { *m = GetNotificationResponse{} }
func (m *GetNotificationResponse) String() string { return proto.CompactTextString(m) }
func (*GetNotificationResponse) ProtoMessage()    {}
func (*GetNotificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_94158a4fda103638, []int{6}
}

func (m *GetNotificationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNotificationResponse.Unmarshal(m, b)
}
func (m *GetNotificationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNotificationResponse.Marshal(b, m, deterministic)
}
func (m *GetNotificationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNotificationResponse.Merge(m, src)
}
func (m *GetNotificationResponse) XXX_Size() int {
	return xxx_messageInfo_GetNotificationResponse.Size(m)
}
func (m *GetNotificationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNotificationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNotificationResponse proto.InternalMessageInfo

func (m *GetNotificationResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetNotificationResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetNotificationResponse) GetData() []*NotificationResult {
	if m != nil {
		return m.Data
	}
	return nil
}

type NotificationResult struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ThingName            string   `protobuf:"bytes,2,opt,name=thingName,proto3" json:"thingName,omitempty"`
	ThingSerial          string   `protobuf:"bytes,3,opt,name=thingSerial,proto3" json:"thingSerial,omitempty"`
	ThingDisplayName     string   `protobuf:"bytes,4,opt,name=thingDisplayName,proto3" json:"thingDisplayName,omitempty"`
	GatewayName          string   `protobuf:"bytes,5,opt,name=gatewayName,proto3" json:"gatewayName,omitempty"`
	GatewayDisplayName   string   `protobuf:"bytes,6,opt,name=gatewayDisplayName,proto3" json:"gatewayDisplayName,omitempty"`
	GatewayMacAddress    string   `protobuf:"bytes,7,opt,name=gatewayMacAddress,proto3" json:"gatewayMacAddress,omitempty"`
	ZoneName             string   `protobuf:"bytes,8,opt,name=zoneName,proto3" json:"zoneName,omitempty"`
	ZoneDisplayName      string   `protobuf:"bytes,9,opt,name=zoneDisplayName,proto3" json:"zoneDisplayName,omitempty"`
	Status               int32    `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	Type                 int32    `protobuf:"varint,11,opt,name=type,proto3" json:"type,omitempty"`
	Template             string   `protobuf:"bytes,12,opt,name=template,proto3" json:"template,omitempty"`
	State                int32    `protobuf:"varint,13,opt,name=state,proto3" json:"state,omitempty"`
	Description          string   `protobuf:"bytes,14,opt,name=Description,proto3" json:"Description,omitempty"`
	DescriptionVN        string   `protobuf:"bytes,15,opt,name=descriptionVN,proto3" json:"descriptionVN,omitempty"`
	AlertType            int32    `protobuf:"varint,16,opt,name=AlertType,proto3" json:"AlertType,omitempty"`
	DateTime             string   `protobuf:"bytes,17,opt,name=DateTime,proto3" json:"DateTime,omitempty"`
	Acknowledged         int32    `protobuf:"varint,18,opt,name=Acknowledged,proto3" json:"Acknowledged,omitempty"`
	AlertStatus          int32    `protobuf:"varint,19,opt,name=AlertStatus,proto3" json:"AlertStatus,omitempty"`
	DeviceId             int32    `protobuf:"varint,20,opt,name=DeviceId,proto3" json:"DeviceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationResult) Reset()         { *m = NotificationResult{} }
func (m *NotificationResult) String() string { return proto.CompactTextString(m) }
func (*NotificationResult) ProtoMessage()    {}
func (*NotificationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_94158a4fda103638, []int{7}
}

func (m *NotificationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationResult.Unmarshal(m, b)
}
func (m *NotificationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationResult.Marshal(b, m, deterministic)
}
func (m *NotificationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationResult.Merge(m, src)
}
func (m *NotificationResult) XXX_Size() int {
	return xxx_messageInfo_NotificationResult.Size(m)
}
func (m *NotificationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationResult.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationResult proto.InternalMessageInfo

func (m *NotificationResult) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NotificationResult) GetThingName() string {
	if m != nil {
		return m.ThingName
	}
	return ""
}

func (m *NotificationResult) GetThingSerial() string {
	if m != nil {
		return m.ThingSerial
	}
	return ""
}

func (m *NotificationResult) GetThingDisplayName() string {
	if m != nil {
		return m.ThingDisplayName
	}
	return ""
}

func (m *NotificationResult) GetGatewayName() string {
	if m != nil {
		return m.GatewayName
	}
	return ""
}

func (m *NotificationResult) GetGatewayDisplayName() string {
	if m != nil {
		return m.GatewayDisplayName
	}
	return ""
}

func (m *NotificationResult) GetGatewayMacAddress() string {
	if m != nil {
		return m.GatewayMacAddress
	}
	return ""
}

func (m *NotificationResult) GetZoneName() string {
	if m != nil {
		return m.ZoneName
	}
	return ""
}

func (m *NotificationResult) GetZoneDisplayName() string {
	if m != nil {
		return m.ZoneDisplayName
	}
	return ""
}

func (m *NotificationResult) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *NotificationResult) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *NotificationResult) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

func (m *NotificationResult) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *NotificationResult) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *NotificationResult) GetDescriptionVN() string {
	if m != nil {
		return m.DescriptionVN
	}
	return ""
}

func (m *NotificationResult) GetAlertType() int32 {
	if m != nil {
		return m.AlertType
	}
	return 0
}

func (m *NotificationResult) GetDateTime() string {
	if m != nil {
		return m.DateTime
	}
	return ""
}

func (m *NotificationResult) GetAcknowledged() int32 {
	if m != nil {
		return m.Acknowledged
	}
	return 0
}

func (m *NotificationResult) GetAlertStatus() int32 {
	if m != nil {
		return m.AlertStatus
	}
	return 0
}

func (m *NotificationResult) GetDeviceId() int32 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*Thing)(nil), "Thing")
	proto.RegisterType((*SimpleTemplate)(nil), "SimpleTemplate")
	proto.RegisterType((*Property)(nil), "Property")
	proto.RegisterType((*GetNotificationRequest)(nil), "GetNotificationRequest")
	proto.RegisterType((*GetNotificationResponse)(nil), "GetNotificationResponse")
	proto.RegisterType((*NotificationResult)(nil), "NotificationResult")
}

func init() { proto.RegisterFile("simple-notification/message.proto", fileDescriptor_94158a4fda103638) }

var fileDescriptor_94158a4fda103638 = []byte{
	// 701 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x6e, 0xd2, 0x38, 0xb1, 0xa7, 0x6d, 0xd2, 0x6e, 0xab, 0x76, 0x15, 0x21, 0x28, 0x56, 0x05,
	0xe5, 0xcf, 0x48, 0x85, 0x17, 0xa8, 0xa8, 0x8a, 0x38, 0x34, 0x42, 0x4e, 0xc4, 0xdd, 0xb5, 0x87,
	0x60, 0x91, 0xd8, 0xc1, 0x5e, 0xb7, 0x4a, 0x4f, 0x3c, 0x06, 0x2f, 0xc1, 0x13, 0x72, 0x61, 0x77,
	0xd6, 0x89, 0xd7, 0x49, 0x90, 0xb8, 0xed, 0xf7, 0xcd, 0x78, 0x67, 0xe7, 0x9b, 0xf9, 0x12, 0x78,
	0x9a, 0xc7, 0xd3, 0xd9, 0x04, 0xdf, 0x24, 0xa9, 0x88, 0xbf, 0xc6, 0x61, 0x20, 0xe2, 0x34, 0x79,
	0x3b, 0xc5, 0x3c, 0x0f, 0xc6, 0xe8, 0xcd, 0xb2, 0x54, 0xa4, 0xee, 0x9f, 0x06, 0x74, 0x7c, 0xfc,
	0x51, 0x60, 0x2e, 0xd8, 0x23, 0xb0, 0xc4, 0xb7, 0x38, 0x19, 0xf3, 0xc6, 0x69, 0xe3, 0x7c, 0xe7,
	0xa2, 0xed, 0x8d, 0x14, 0xf2, 0x35, 0xc9, 0x4e, 0xa1, 0x33, 0x0e, 0x04, 0xde, 0x07, 0x73, 0xde,
	0xac, 0xc5, 0x17, 0x34, 0x73, 0xc1, 0x16, 0x28, 0x0b, 0x4a, 0xc8, 0xb7, 0x6b, 0x29, 0x4b, 0x9e,
	0xf5, 0xa1, 0xf5, 0x90, 0x26, 0xc8, 0x5b, 0xb5, 0x38, 0x71, 0xec, 0x19, 0x74, 0xc3, 0x22, 0x17,
	0xe9, 0x14, 0xb3, 0x41, 0x31, 0xbd, 0xc5, 0x8c, 0x5b, 0x32, 0xcb, 0xf1, 0x57, 0x58, 0xf6, 0x18,
	0x60, 0x1a, 0x84, 0x97, 0x51, 0x94, 0xc9, 0x56, 0xb8, 0x4d, 0x39, 0x06, 0xc3, 0x18, 0xb4, 0xc4,
	0x7c, 0x86, 0xbc, 0x2d, 0x23, 0x96, 0x4f, 0x67, 0x76, 0x04, 0xd6, 0x5d, 0x30, 0x29, 0x90, 0x77,
	0x28, 0x5d, 0x03, 0xf7, 0x1a, 0x6c, 0x1f, 0xf3, 0x59, 0x9a, 0xe4, 0xc8, 0x8e, 0xa1, 0x2d, 0xbf,
	0x2e, 0x26, 0x82, 0xda, 0xb7, 0xfd, 0x12, 0xc9, 0xae, 0x76, 0x31, 0xcb, 0xd2, 0xec, 0x46, 0xeb,
	0x46, 0xcd, 0x3b, 0x7e, 0x8d, 0x73, 0x7f, 0x37, 0xc0, 0x1a, 0x95, 0x2a, 0xed, 0x44, 0x71, 0x2e,
	0x7b, 0x9d, 0x0f, 0x82, 0x29, 0xd2, 0x55, 0x8e, 0x6f, 0x52, 0xea, 0x75, 0x89, 0x0a, 0xe9, 0x7b,
	0xe8, 0xac, 0x6a, 0xe7, 0x98, 0xc5, 0xc1, 0x84, 0x74, 0x73, 0xfc, 0x12, 0xb1, 0x17, 0x00, 0x72,
	0x4c, 0x33, 0xcc, 0x44, 0x8c, 0xb9, 0xd4, 0x6c, 0x5b, 0x6a, 0xe6, 0x78, 0x9f, 0x35, 0x35, 0xf7,
	0x8d, 0x20, 0x7b, 0x65, 0x88, 0x6f, 0x91, 0xb8, 0x3d, 0x6f, 0x48, 0xe3, 0x1f, 0x95, 0x74, 0x35,
	0x05, 0xf7, 0x0c, 0xba, 0xf5, 0xd8, 0xf2, 0x55, 0x8d, 0xea, 0x55, 0xee, 0x7b, 0xb0, 0x17, 0xa5,
	0x36, 0xc5, 0x2b, 0x4d, 0x9b, 0x75, 0x4d, 0x8f, 0x3f, 0xa2, 0x18, 0x18, 0x2b, 0xb7, 0xd8, 0x2f,
	0x99, 0x1f, 0xa6, 0x45, 0xa2, 0x05, 0xb6, 0x7c, 0x0d, 0x8c, 0xde, 0x9b, 0x66, 0xef, 0xee, 0xcf,
	0x06, 0x9c, 0xac, 0x5d, 0x54, 0xce, 0x8a, 0x43, 0x27, 0x2f, 0xc2, 0x50, 0x8d, 0x5f, 0x0f, 0x6b,
	0x01, 0xff, 0x67, 0x5a, 0xec, 0x39, 0xb4, 0xa2, 0x40, 0x04, 0x52, 0x6b, 0xa5, 0xe7, 0xa1, 0xb7,
	0x52, 0x42, 0x0e, 0xdd, 0xa7, 0x04, 0xf7, 0x97, 0x05, 0x6c, 0x3d, 0xc8, 0xba, 0xd0, 0x8c, 0xa3,
	0xb2, 0x09, 0x79, 0x92, 0xbe, 0x71, 0xc8, 0x22, 0x83, 0x6a, 0xac, 0x15, 0xa1, 0x36, 0x82, 0xc0,
	0xd0, 0x1c, 0xb0, 0x49, 0xb1, 0x97, 0xb0, 0x4f, 0xf0, 0xca, 0x58, 0x9c, 0x16, 0xa5, 0xad, 0xf1,
	0xea, 0xb6, 0xd2, 0x6e, 0x94, 0xa6, 0x0d, 0x62, 0x52, 0xcc, 0x03, 0x56, 0x42, 0xf3, 0xbe, 0x36,
	0x25, 0x6e, 0x88, 0xb0, 0xd7, 0x70, 0x50, 0xb2, 0x37, 0x95, 0xa9, 0xb4, 0x4b, 0xd6, 0x03, 0xd2,
	0xbf, 0xb6, 0xf2, 0x2a, 0xdd, 0xa9, 0x9d, 0xb7, 0xc4, 0xec, 0x1c, 0x7a, 0xea, 0x6c, 0x96, 0x75,
	0x28, 0x65, 0x95, 0xa6, 0x99, 0x8b, 0x40, 0x14, 0x39, 0x07, 0x52, 0xb1, 0x44, 0x4b, 0xe7, 0xee,
	0x18, 0xce, 0xed, 0x1b, 0x8b, 0xbd, 0xab, 0x2b, 0x2e, 0x7f, 0x4d, 0xe4, 0x46, 0xa9, 0x2f, 0x91,
	0xef, 0xe9, 0x8d, 0x22, 0xa0, 0x34, 0xba, 0xc2, 0x3c, 0xcc, 0xe2, 0x99, 0x1a, 0x1a, 0xef, 0x6a,
	0x8d, 0x0c, 0x8a, 0x9d, 0xc1, 0x5e, 0x54, 0xc1, 0x2f, 0x03, 0xde, 0xa3, 0x9c, 0x3a, 0xa9, 0xe6,
	0x7a, 0x39, 0x91, 0xdb, 0x3f, 0x52, 0x4f, 0xda, 0xa7, 0x0a, 0x15, 0xa1, 0xde, 0x75, 0x25, 0xab,
	0x8d, 0x62, 0xd9, 0xe6, 0x81, 0x7e, 0xd7, 0x02, 0xab, 0x2d, 0xbc, 0x0c, 0xbf, 0x27, 0xe9, 0xfd,
	0x04, 0xa3, 0x31, 0x46, 0x9c, 0xd1, 0xc7, 0x35, 0x4e, 0xbd, 0x92, 0x2e, 0x1b, 0x6a, 0x21, 0x0e,
	0x29, 0xc5, 0xa4, 0xa8, 0x02, 0xde, 0xc5, 0x21, 0x7e, 0x8a, 0xf8, 0x11, 0x85, 0x97, 0xf8, 0xe2,
	0x01, 0x7a, 0xe6, 0x66, 0x0e, 0xef, 0x42, 0xf6, 0x04, 0xda, 0x1f, 0x32, 0x54, 0x02, 0xd8, 0x5e,
	0x69, 0xb9, 0xbe, 0xe3, 0x2d, 0x3c, 0xe3, 0x6e, 0xb1, 0x6b, 0xe8, 0xad, 0x18, 0x8a, 0x9d, 0x78,
	0x9b, 0xbd, 0xda, 0xe7, 0xde, 0x3f, 0xbc, 0xe7, 0x6e, 0xdd, 0xb6, 0xe9, 0xaf, 0xe3, 0xdd, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x09, 0xa3, 0xde, 0x13, 0x5f, 0x06, 0x00, 0x00,
}
